### ISSUE TITLE
[FE] - Position list - Table

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#103]
- Get data from subgraph
- Show paginated table

https://wireframepro.mockflow.com/view/M6eaccdb4e3776bf4fd576d04b0095a191590507310129#/page/9c5a896b3d6048b98c0c4df2f702d5c6

**Comment by mariano-aguero** [comment]
Done by this https://github.com/gnosis/conditional-tokens-explorer/pull/128
