### ISSUE TITLE
[FE] Redeem condition resolved

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#165]
Check in the redeem section, if the condition is really resolved

- Check using the modal
- Check using the inpu

![Screenshot_20200903_142634](https://user-images.githubusercontent.com/1144028/92147804-fb76f580-edf1-11ea-8083-42d9f15b12ee.png)

**Comment by hpmaxi** [comment]
Can't reproduce. `0xe9dfac9e4fd6e32ade881dc659fee8cb4bbbb1346630b1fd857a3a4bb92812ea` is a resolved condition and `0x00fc8952b001bfe940a770cb406e1126b7f09469ce01e62743ad3c2447d1ef87` isn't resolved.

**Comment by elena-zh** [comment]
I have verified the issue. It is not reproducible for me as well.
