### ISSUE TITLE
[FE] In the redeem section, add modal with the status of the transaction

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#166]
In the redeem section, add modal with the status of the transaction
Also, the modal should be added to the
- Report payouts page
- Merge positions page

The modal should contain OK button, which closes the pop-up and leaves a user on the page he/she is currently on.

**Comment by elena-zh** [comment]
Also, it would be nice to add a loader when a transaction is being processed.
