### ISSUE TITLE
[FE] Collateral custom is not displayed in the position details

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#169]
![Screenshot_20200903_150151](https://user-images.githubusercontent.com/1144028/92150827-6d513e00-edf6-11ea-9004-ac86e2288b6f.png)
![Peek 03-09-2020 15-02](https://user-images.githubusercontent.com/1144028/92150963-a5588100-edf6-11ea-9f5a-df1d32dedae2.gif)

**Comment by hpmaxi** [comment]
Can't reproduce
