### ISSUE TITLE
[FE] Apply decimals to the amount displayed in the ERC1155 column

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#174]
![Screenshot_20200903_175606](https://user-images.githubusercontent.com/1144028/92166583-35a2c000-ee0f-11ea-8652-a75a00022667.png)

**Comment by mariano-aguero** [comment]
Maybe, we can apply the same solution for the position list

**Comment by lmcorbalan** [comment]
It should format the amount using `collateral token` decimals. Though it may get tricky to do when collateral token is not one from `allowed tokens list` in configs.
Maybe format the amount when the collateral in a `allowed token`, since when it isn't we show its address under `COLLATERAL` column.
