### ISSUE TITLE
[Subgraph] - Position List - Balances (ERC20) - Add Wrapper to the subgraph

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#186]
would be nice to have wrapper information in the subgraph.

**Comment by mariano-aguero** [comment]
Already done

See https://github.com/cag/1155-to-20

It is on all networks at this address https://etherscan.io/address/0xDE6943f3717738038159a406FF157d4eb3238c1B the Wrapped1155Factory
