### ISSUE TITLE
[FE] - Positions List - Wrap Unwrap buttons + modal

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#187]
Design: https://zpl.io/2GZznJ9 / https://zpl.io/2GZznJ9 / https://zpl.io/bJyELkn

**Comment by elena-zh** [comment]
According to the discussion in #235, 
1. hide or disable Wrap/Unwrap action buttons in Positions list when a user is not logged in
2. Show a message '"Connect to a wallet to display" in the COLLATERAL WRAPPING section on a position details section when a user is not logged in

**Comment by elena-zh** [comment]
Wrap/Unwrap action buttons in Positions list are hidden when a user is not logged in
Wrap/Unwrap action buttons are disabled on a Position details page when a user is not logged in. Amounts are hidden.
