### ISSUE TITLE
ERC1155-ERC20 Wrapper

### ISSUE THREAD

**Issue by fvictorio** [gnosis/conditional-tokens-explorer#2]
Opening here since the wrapper will be important for this project, but of course it should be done in a different repository.

This is a minimal interface that I think could work:

```solidity
contract ERC1155Wrapper is ERC1155TokenReceiver {
  ERC1155 public erc1155;
  mapping(uint256 => address) idToToken;
  mapping(address => uint256) tokenToId;

  constructor (ERC1155 _erc1155) {
    // there is one ERC1155Wrapper for each ERC1155
    // it's possible to have one contract to rule them all, but I don't think the extra complexity is worth it
    erc1155 = _erc1155;
  }

  function onERC1155Received(address _operator, address _from, uint256 _id, uint256 _value, bytes calldata _data) external returns(bytes4) {
    // create an erc20 for the given `id` if one doesn't exist already
    ERC20 erc20 = getOrCreateToken(id);

    // keep the 1155 tokens and mint that amount of erc20 for the original owner
    erc20.mint(_from, _value);

    return bytes4(keccak256("onERC1155Received(address,address,uint256,uint256,bytes)"));
  }

  function unwrap (ERC20 erc20, uint256 value) external {
    erc20.burn(msg.sender, value);
    
    ERC1155.safeTransferFrom(address(this), msg.sender, tokenToId(address(erc20)), value);
  }
}
```

I didn't include `onERC1155BatchReceived`, but it's probably easy to implement if the rest is done.

Some open questions:
1) This snippet is missing the part where we check if the received 1155 comes indeed from the contract specified in the constructor. I think this might be just `require(msg.sender == address(erc1155))` but I'm not really sure.
2) This means that the first user to wrap some id will incur in the cost of deploying the erc20. Is there a better way?
3) Both the wrapping and the unwrapping send the resulting token to the original owner. Is it necessary to have more flexibility here? For example, `onERC1155Received` could use the `_data` argument to optionally extract the recipient, and `unwrap` could have a `recipient` parameter.

cc @cag @georgi87

**Comment by cag** [comment]
1. Yes.
2. An ERC-20 has to be made by somebody... But getOrCreateToken could be public so it could be anyone.
3. Sure, that sounds fine. I don't have any strong opinions about this feature, but it might be worth it to have for somebody. At least I don't see much of a downside.

**Comment by cag** [comment]
https://gist.github.com/cag/41c68a6402fc7c80b03f72cbf42f27f6 <- initial implementation

**Comment by cmalfesi** [comment]
@cag Please, share here the status of this ticket and how we can test it or consume the contract.

**Comment by mariano-aguero** [comment]
Already done

See https://github.com/cag/1155-to-20

It is on all networks at this address https://etherscan.io/address/0xDE6943f3717738038159a406FF157d4eb3238c1B the Wrapped1155Factory
