### ISSUE TITLE
User is logged in under Account 1 when Account 2 is selected as active in Metamask

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#206]
**Steps:** 
1. Connect to wallet Account 1 in Metamask
2. Disconnect
3. Create Account 2 in the Metamask, select it as a main one
4. Connect to wallet using Metamask

**Actual Result:** Account 1 is connected. System does not force connection to the 2nd account in the Metamask
![account2.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/463aca56-7d8c-49fe-880a-9c3407b10ab9)
![force connection.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/26c390ce-279b-46a3-b89b-be7f9f7a2c79)

**Expected Result:** System should force the connection with Account 2. After accepting all the permissions Account 2 should be connected

**Comment by mariano-aguero** [comment]
Related to #257

**Comment by elena-zh** [comment]
I have checked the issue. 
Seems to me still unfixed, due to  a user is not prompted to connect a new account right after its creation in the Metamask (nothing happens until a user decides to open the metamask once again and click on the connect button)
![Screenshot_1](https://user-images.githubusercontent.com/70885163/94002947-3b9f1780-fda3-11ea-8999-85ac6c85a314.jpg)


Can we automatically call this connection window right after a new account creation in the Metamask? 
![image](https://user-images.githubusercontent.com/70885163/94002925-35a93680-fda3-11ea-8cc2-e871625dda4f.png)

**Comment by gabitoesmiapodo** [comment]
I don't think just creating a new account will connect it. The user will probably have to explicitly connect the new account.

**Comment by elena-zh** [comment]
Yes, that is the issue. We can call Metamask confirmation modals when perform any transactions/1st connection with the account. 
The question is that can we call such a connection pop-up right after an account creation as well? 
If not, user will have to do connection manually (and I will close the issue). If yes, It would be nice to implement such a possibility.

**Comment by mariano-aguero** [comment]
> The question is that can we call such a connection pop-up right after an account creation as well?

Can't be done, metamask doesn't expose an event for such kind of behavior (account created, so we can take some action after that, see this for more https://docs.metamask.io/guide/ethereum-provider.html#events). Also this action possibly could be a little invasive (maybe), we cannot assume that if an user created an account it is because she/he wants to connect it

**Comment by elena-zh** [comment]
Thanks!
I'm closing the issue.
