### ISSUE TITLE
[FE] Implement search feature for positions which belong to a certain condition in the Positions page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#207]
Currently, a user only can search for positions using positionId and filter grid by Collateral. 
However, it is too difficult to trace which positions belong to a certain condition. 
It would be nice to gave a search feature which will show positions which belong to a certain conditionid

**Comment by gabitoesmiapodo** [comment]
I'm closing this, it's (more or less) a duplicate of https://github.com/gnosis/conditional-tokens-explorer/issues/341 and https://github.com/gnosis/conditional-tokens-explorer/issues/337
