### ISSUE TITLE
[FE] Implement a warning pop-up to prevent data loss when leaving a page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#211]
When a user starts filling any form and wants to leave a page he/she currently working with, show warning pop-up:
“Are you sure you want to leave this page? The changes you made will be lost.” with 'Cancel' and 'Leave' buttons. 

- Cancel button closes the pop-up, user stays on the page, the changes are saved
- Leave button closes pop-up, redirects the user to another page, the changes on the edited page are not saved.

It would be nice to have a warning pop-up on the next pages: 
- Prepare condition page
- Split position page
- Merge positions
- Report  payouts page
- Redeem positions page

https://drive.google.com/file/d/19nHqF7izuKwZyPWlfCT7NtOeYeGm9LFb/view

Also, it would be nice to add the modal before a page auto-reload when user changes  an account in the connected app (metamask or any other connected one)

**Comment by mariano-aguero** [comment]
> Also, it would be nice to add the modal before a page auto-reload when user changes an account in the connected app (metamask or any other connected one)

Created an issue for this https://github.com/gnosis/conditional-tokens-explorer/issues/536

**Comment by elena-zh** [comment]
Verified. 
Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/537#issuecomment-718662232)
