### ISSUE TITLE
Impossible to close the connection pop-up once it is called

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#212]
**Steps:** 
1. Click on the 'Connect to wallet' button 
OR call the connection pop-up by other possible way
2. Try to close it

**Actual result:** It is impossible to close the connection pop-up once it has been called (until a user logs in or reloads a page). It is displayed above other pages when user navigates in the app using the browsers action buttons. 
https://drive.google.com/file/d/1rm-sWyagT_0f2MLIs4038FsFDsYnsE2-/view

**Expected Result:** close the pop-up by clicking outside its area

**Comment by gabitoesmiapodo** [comment]
See https://github.com/gnosis/conditional-tokens-explorer/pull/225
