### ISSUE TITLE
[FE] Add 'Custom' option for filtering Positions grid

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#213]
When split positions, users have a possibility to 'Add Custom Collateral' instead of using the predefined ones. 
However, it is difficult to fine them on the 'Positions' grid as there is no such filter option there. 
It would be nice to add 'Custom' option for filtering Positions grid
![custom.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bdb132ce-f664-40f3-aaa8-c331034c25d3)

**Comment by gabitoesmiapodo** [comment]
This will be implemented on https://github.com/gnosis/conditional-tokens-explorer/issues/341 among other things.

However I'm referencing this issue there.
