### ISSUE TITLE
'Condition is not valid' pop-up appears when click on the QuestionId/Reporting address on the Conditions page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#217]
**Steps:** 
1. Open Conditions page
2. Click on the QuestionID on any grid line
OR
Click on the Reportind Address on any grid line
![click.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2d2fc0dc-9d4f-4523-9b0c-79e491f42cb7)

**Actual Result:** 'Condition is not valid' pop-up appears
![error.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5643598b-a682-49de-8f8c-67f0b201d032)

**Expected Result:** Condition details are opened when click on any grid line with any condition

**Comment by mariano-aguero** [comment]
Mmm seems to be a configuration problem, or maybe a race condition with thegraph (waiting until thegraph index the condition)
We need to check this

**Comment by hpmaxi** [comment]
Duplicated of #248
