### ISSUE TITLE
UI: COLLATERAL does not fit 1 line in the pop-up on the 'Redeem positions' page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#220]
**Steps:** 
1. Open Redeem positions page
2. Click on the Select position button

**AR:** COLLATERAL does not fit 1 line in the pop-up
![collateral.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/734f25ec-5e53-490f-81cb-814a005169f8)

**ER:** COLLATERAL fits 1 line in the pop-up

**Comment by gabitoesmiapodo** [comment]
Hm, it seems "Select Position" is broken site wide (not only in "Split Position").

I'll wait until it's fixed on https://github.com/gnosis/conditional-tokens-explorer/issues/244
