### ISSUE TITLE
Error message is displayed when split positions after the 1st rejection

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#221]
**Steps:** 
1. Open Split position page
2. Fill in all the requires fields with valid data, press on Split button
3. Reject transaction (split position) in the Metamask
4. Do not close the form and fill in the fields with the same data, press on split 
5. Confirm the transaction in the Metamask

**Actual Result:** 
Error message appears. However, the transaction is approved, positions are created in the system 
![error.jfif](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d02d4032-eb3c-4172-8e70-86d19e57281e)
![created.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0f78bfa2-b960-41e2-88e1-c2e27f053830)
![postitons are created.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e0dfe667-3cc5-4e5f-ac2f-2785bc4fac96)

**Expected Result:** Error message should appear on the 1st action (rejection)
Then the next transaction should be successfully processed (without any warnings)

**Comment by davidalbela** [comment]
Fixed on PR https://github.com/gnosis/conditional-tokens-explorer/pull/251

**Comment by elena-zh** [comment]
Verified
