### ISSUE TITLE
Add custom token: Error messages for the contract validations show code/no validation message about unsuccessful attempt of unlocking an account

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#223]
UPD: 17/09/2020
Validation messages are not displayed at all not on the pop-uo, however, they are displayed in console
![image](https://user-images.githubusercontent.com/70885163/93486257-a61c0780-f90c-11ea-8701-7c509a628616.png)

Related to #202

1. Error messages for the contract validations show code: see the video: 
https://drive.google.com/file/d/1UWUkgwc-cHCm_I1pQiU-4sijvPLwVBPK/view
**Expected result:** messages are written in understandable to an end user manner

2. No validation message about unsuccessful attempt of unlocking an account (see the video)
 https://drive.google.com/file/d/1kiGBF0UK4GaG6wDyXEEYXKZwF65DgOoT/view

**Expected result:** Error message should appear on the window

**Comment by davidalbela** [comment]
I think does not make sense to show errors or warnings from external wallets that rejects a transaction. If you reject the selected action from Metamask or any other wallet connected via WalletConnect the user rejected on the wallet app, not on the explorer app. What do you think?

**Comment by elena-zh** [comment]
Currently, 'User denied transaction signature' message si displayed when reject a transaction on the split positions page.
![image](https://user-images.githubusercontent.com/70885163/94027571-a82a0e80-fdc3-11ea-8a68-ceceec10e2ee.png)

However, your error message is more informative. It would be nice to use it across the app for this action.

**Comment by elena-zh** [comment]
Validation messages started to show code again in the latest app version (24.09.2020) 
![image](https://user-images.githubusercontent.com/70885163/94133784-c77b7700-fe69-11ea-80ea-a4e4d683ac12.png)

@davidalbela , please, take a look into the latest deployments.
