### ISSUE TITLE
Remove a possibility to enter negative amounts into the outcomes field

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#224]
Remove a possibility to enter negative amounts into the outcomes field using arrows and/or entering manually . 
When using arrow, it would be nice to start count from 2 (minimal acceptable value) 
![out.jfif](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7f19b3cb-4314-48e8-a2a7-d5095bbd729e)

**Comment by davidalbela** [comment]
I think this task is not useful, the input accept number type from typescript and it's already showing the error message if you type negative numbers `-` or if you try to input decimals. Besides, the user must know that the outcomes should be entering numbers and the tool does not allow to submit in other case.

**Comment by gabitoesmiapodo** [comment]
Working on this will prove difficult and time consuming.

Anyways: input is validated and the user is told what the valid inputs are, so nothing will be submitted unless allowed values are used.
