### ISSUE TITLE
[FE] Add an ability to remove the selected position from the modal on the Redeem position page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#227]
Once a position has been selected, user cannot remove it (only change). 
see the video: https://drive.google.com/file/d/1udugXRF_g5KPS5RBxsJZOsOdJa3GUz7K/view
It would be nice to have a possibility to remove it and then select a new one. As an option,  to have a button with a delete icon (like a button) in the input to remove the selection.
Additionally, user should be able to call Select Position pop-up by pressing on the Position field (described in  #376 )

Note:  list of positions do not appear on the 1st call (only on the 2nd one) on the video. The issue is described in #198 and is currently fixed.

**Comment by hpmaxi** [comment]
Closed by #390
