### ISSUE TITLE
[UI/UX] WalletConnect pop-up header seems to overlap the menu

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#231]
related to #225

**Steps:**
Connect with an Account using WalletConnect
Close the connection in the mobile app
Reload the page

**Actual Result:** pop-up header seems to overlap the menu
![still.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/77e16cce-b47e-4578-b2b0-ebfd94a19353)
**Expected:** It would be nice to reduce some transparency on the overlay to remove 'overlapping' issue

**Comment by gabitoesmiapodo** [comment]
I don't think we should be spending time on this, it's a negligible issue with an external module which for all we know could change tomorrow and break again?
