### ISSUE TITLE
Incorrect pagination in Positions/Conditions grid inside of the Select Position/Select Condition pop-ups

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#241]
**Steps**: 
1. call Select Condition pop-up (from Split positions, Merge positions, redeem positions, report payout pages)
2. call Select Position pop-up (from Merge positions, redeem positions, report payout pages)
3. Verify pagination for  Positions/Conditions grids

**AR:** pagination shows 10 rows per page, however, 5 rows are displayed
![show all 10.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2a39a7c9-7f84-426a-9b06-57229c393888)

**ER:** show 10 positions per page
OR
add option to show 5 positions per page (for these modal windows)

**Comment by davidalbela** [comment]
weird, I counted the selected number of rows per page for both grids/lists, unless you are in the last page.

**Comment by elena-zh** [comment]
@davidalbela , yes. I mean
![Screenshot_3](https://user-images.githubusercontent.com/70885163/93765523-b50cfd80-fc1d-11ea-803a-4a7f8a267e86.jpg)
