### ISSUE TITLE
[FE / UI] Add Split Position Result Modal / Info

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#243]
We need to do something after splitting a position.

Adding a modal with a list of the split positions should be enough, but we can't just do nothing.

**Maybe this would do it:**

- Title: "Split Positions"
- Table with the usual table columns for "Select Position."
- It should be possible to click each row to navigate to each position's details page. Also to copy the position's ID, etc.
- An "OK" button.

**Comment by elena-zh** [comment]
Verified. Looks good to me. 
However, I have created 2 connected issues:
1.Split Position Result Modal window appears when transaction is failed #276

2. Split Position Result Modal window  UI bugs #277
