### ISSUE TITLE
[Bug / FE] Conditions / Positions List clicking error

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#248]
**On conditions list:** clicking on a reporting address / question id value takes the user to an `undefined` condition details page, so there's a problem there. Clicking on an outcomes / status value does nothing. I think that except for the copy and dropdown buttons, we should take the user to the condition details page when clicking anywhere on the row.

**On positions list:** nothing happens when clicking on a collateral or ERC1155 value. We should fix this too.

![Sep-14-2020 18-29-20](https://user-images.githubusercontent.com/4015436/93141537-bb015c80-f6ba-11ea-9841-6cc1787b963c.gif)

![Sep-14-2020 18-30-28.gif](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/9932c2e3-c502-4fb0-9a86-7a550e85d583)

**Comment by elena-zh** [comment]
The current ticket is verified and closed. 
However, still nothing happens when clicking on a collateral on the Positions list. I have created a separate ticket for this issue #275
