### ISSUE TITLE
Setup - CI/CD

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#25]
Setup continuous integration on Github repository
Automatic deployment of PRs to Netlify or AWS (or similar tool)
Define and configure automatic deployments (CD) to staging and production environments

**Comment by cmalfesi** [comment]
Wrong Epic

**Comment by davidalbela** [comment]
The PR #32 will add the Travis CI for different automatically deployments:
- Pull request reviews (e.g:  https://pr32--conditionaltokensexplorer.review.gnosisdev.com). Link will be automatically sent to the PR by the bot.
- Tag release reviews (e.g: https://v100--conditionaltokensexplorer.review.gnosisdev.com).
- Commit or merge into `develop` branch: a job will deploy automatically into **development** environment cluster.
- Commit or merge into `main` branch: a job will deploy automatically into **staging** environment cluster.
- Tag release: It will prepare a build to deploy the release into production.
