### ISSUE TITLE
[FE] Split position: Sometimes the Amount field may appear pre-filled with a value after login

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#252]
The issue **is not always reproducible**, but I faced it several times. here are the steps: 
1. Open Split positions page as a not logged in user
2. Fill in the required fields
3. Edit a partitioning, save changes
3. Press on the Unlock button
4. Log in using metamask

**AR:** Amount field may appear pre-filled with 0.000000000001 value
![amount field - after login.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/12601724-d00c-487f-8a70-cf905ce5f806)

**ER:** amount is 0.00

**Comment by hpmaxi** [comment]
Trying to reproduce this I got this error. 
```
Unhandled Rejection (Error): contract not deployed (contractAddress="0x6b175474e89094c44da98b954eedeac495271d0f", operation="getDeployed", version=4.0.47)
▶ 2 stack frames were collapsed.
async ERC20Service.balanceOf
src/services/erc20.ts:67
```

**Comment by elena-zh** [comment]
I have rechecked the issue. It is not reproducible so far. 
I'm closing the bug.
