### ISSUE TITLE
[FE] Add a possibility to search positions/conditions created by currently connected wallet account

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#258]
Add an option to search positions/conditions on the 'Positions'/'Conditions' pages by 'Created by me' option. 
As soon as the option selected, run a query which searches for positions/conditions which are created by the currently connected **wallet address** with the app. 
If a user is not logged in, disable 'Created by me' option for positions/conditions search

**Comment by gabitoesmiapodo** [comment]
I'm adding this as an option on https://github.com/gnosis/conditional-tokens-explorer/issues/341
