### ISSUE TITLE
In the position list section, token custom icon should be displayed in all the rows

### ISSUE THREAD

**Issue by hpmaxi** [gnosis/conditional-tokens-explorer#272]
> ![Screenshot_20200915_135839](https://user-images.githubusercontent.com/1144028/93241397-a923c600-f75b-11ea-9b41-2e49ebf9e6e6.png)

_Originally posted by @mariano-aguero in https://github.com/gnosis/conditional-tokens-explorer/pull/236#issuecomment-693669992_

**Comment by gabitoesmiapodo** [comment]
It seems there's no issue here anymore, but I'd like @elena-zh to confirm.

**Comment by elena-zh** [comment]
Yes, the issue us fixed. 
I'm closing the ticket.
