### ISSUE TITLE
[FE] Nothing happens when clicking on a collateral on the Positions list

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#275]
Related to the #248, #256

Open positions grid and click on the collateral: nothing happens

**Expected Result:** position details page should be opened.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , the issue seems to be unfixed. 
Still nothing happens when I do a left click on a collateral on the Positions list
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/481770bd-3fdb-4bb1-ab05-4686cd5234c1)

**Comment by gabitoesmiapodo** [comment]
Same as in https://github.com/gnosis/conditional-tokens-explorer/pull/377#issuecomment-700909422 it seems to be working fine on https://conditional-tokens-explorer.dev.gnosisdev.com/ ?

![Sep-29-2020 15-46-56](https://user-images.githubusercontent.com/4015436/94602325-14e15500-026b-11eb-9a25-8410b4d2068c.gif)

**Comment by elena-zh** [comment]
@gabitoesmiapodo ,
Today everything works as expected. I'm closing the task. 
Thanks!
