### ISSUE TITLE
[FE] Split Position Result Modal window appears when transaction is failed

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#276]
Related to #251, #243

Currently, there is no possibility to create positions in the BAT custom collateral (#242)

**Steps:** 
1. Try to split custom BAT collateral --> the transaction will fail 
2. Wait till the loader will be closed

**AR:** Split Position Result Modal window appears with positions info. However, no such positions are created/displayed in the Positions list (due to the transaction is unsuccessful)
![failed-- positions.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c967a282-b82e-4274-b40a-46c1a44a16cf)
![not found.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/08f6930d-9543-428a-8762-abcf3be47f27)

**Expected Result:** Pop-up about the unsuccessful transaction should be displayed

**Comment by hpmaxi** [comment]
```this.provider.waitForTransaction(tx.hash, CONFIRMATIONS_TO_WAIT)``` this doesn't throw an error, and even when it fails you have to wait for that number of confirmations. I tried ```const receipt = await this.provider.getTransactionReceipt(tx.hash)``` for awaiting the receipt and when it fails check that object, what I can see is that logs are empty, but how many logs you have depends on which method is called .
