### ISSUE TITLE
[FE][Bug] ERC1155 sorting on the Positions List table

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#279]
Sorting by ERC1155 amount seems to be broken:

![Screen Shot 2020-09-17 at 10.30.26.png](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/0a4554dc-f764-4d76-ae6b-5b3649d4e0cf)

**Comment by mariano-aguero** [comment]
Also check for the  `ERC20 amount`
