### ISSUE TITLE
[UI/UX] Token unlock Done / Error status

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#280]
It currently looks like this:

![Screen Shot 2020-09-17 at 11.17.59.png](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/ce86f21c-b9b8-4966-99df-f0c7bb6e7945)

We need a design for when there's an error, and for the Done status.

And then implement it.

**Comment by gabitoesmiapodo** [comment]
Here's the new design: https://zpl.io/2jDv4dQ

Currently implementing it.

**Comment by elena-zh** [comment]
There is no any logic implemented to show error messages. 
Verified the next states only: 
 - contract is unlocked
 - contract is successfully unlocked.
