### ISSUE TITLE
[UI/UX] Sort icon placement

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#281]
It seems one of the sort icons in the Conditions List table is on the left (check the Outcomes column), while everywhere else it's on the right.

![Screen Shot 2020-09-17 at 10.35.36.png](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/7cd980f3-e4f7-4b59-ac3b-dbb9265bdff3)

**Comment by elena-zh** [comment]
The same issue is applicable to ERC20 and ERC1155 amounts columns in the 'Positions' list
