### ISSUE TITLE
[FE] Position with 0 amount is displayed on the confirmation pop-up when split a position

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#289]
**Steps:** 
**1.** Create a condition (0x48b7437c8f07385b5163e460373e881b47fd48637d3205a44cba9c0d378e7a17)
**2.** Split 2 positions 
(I have created 2 positions with 2 tokens: 
positions 1: 
 0x0ea867ee4efde6777b6d61f9a998bac73f8b2c42e02d3fd5d94867492f859938
positions 2:
 0x02f8438e9aac84d4dd2dc1c4f7f9fcc7fd101c1113bdac9681dc636bb6482f7a)

**3.** I split the position 2 (0x02f8438e9aac84d4dd2dc1c4f7f9fcc7fd101c1113bdac9681dc636bb6482f7a) and decide to transfer 1 token to the new partition. As a result I get pop-up with the next positions: 
       0x346c4c899fdf653d0da2d970a0791adabd5820b9dbd9ffa00b8ef8da3a314582 --1 token
       0xe4ff4f272dde48ca025e085b761c4d75831d3be92fb8b468ce863cabf0653f03  --**0 token** 

**4 step may be skipped, but anyway:** I split the position 1 ( 0x0ea867ee4efde6777b6d61f9a998bac73f8b2c42e02d3fd5d94867492f859938) and decide to transfer 2 tokens to the new partition. As a result I get pop-up with the next positions: 
       0x346c4c899fdf653d0da2d970a0791adabd5820b9dbd9ffa00b8ef8da3a314582 --**3 tokens**
       0xe4ff4f272dde48ca025e085b761c4d75831d3be92fb8b468ce863cabf0653f03  --**0 token** 
![empty.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/83d1b9ad-7140-4d5d-a701-f2aeec5650cc)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/854bc867-23eb-46e6-a467-4175c9985ed3)

**As a result of these splits I have:** 
Position 1 0x0ea867ee4efde6777b6d61f9a998bac73f8b2c42e02d3fd5d94867492f859938 with 0 tokens
Position 2 0x02f8438e9aac84d4dd2dc1c4f7f9fcc7fd101c1113bdac9681dc636bb6482f7a with 1 token
Position 3  0x346c4c899fdf653d0da2d970a0791adabd5820b9dbd9ffa00b8ef8da3a314582 with 3 
**Position 4 0xe4ff4f272dde48ca025e085b761c4d75831d3be92fb8b468ce863cabf0653f03  with 0 tokens, and it is not displayed on the positions list**

**As I expect here:** we should not show the position with zero balance (Position 4) on the split position confirmation pop-up
or
all the positions which are created after a split should not have a zero balance?

**Comment by elena-zh** [comment]
Some kind of an investigation: 
Position with 0 balance has the same id when split all the positions under a condition.
![with 0 balance.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/daae2668-dc2c-411f-9bad-b8dd90cb206b)
However, it is not displayed in the positions list. "Instead of" a new position (which is not shown in the positions pop-up) appears in the positions list. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/88291ad8-8162-4b24-90a7-fda612ada8d0)
So, from my perspective, a solution to show a 'correct' position id on the pop-up (and not to show a position with 0 balance) would be an appropriate fix for the current issue, imho.

**Comment by davidalbela** [comment]
I will add this to PR #400
