### ISSUE TITLE
[FE] The edited partitioning before login is not saved after a user logs in 

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#292]
The edited partitioning before login is not saved after a user logs in (see the video) Note: the issue with amount field on the video is described here: #252
https://drive.google.com/file/d/1HscxRWRKrSb8_e1AOgjIt_QYhaMJo04-/view

Related to #253

**Comment by gabitoesmiapodo** [comment]
We could probably make this a bit easier by not letting the user use this feature without connecting first?

**Comment by elena-zh** [comment]
I'm closing the issue due to it is no longer relevant: 'Edit Partition' button is disabled to a not connected user.
