### ISSUE TITLE
Split position: Amount field is enabled to a not logged in user

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#298]
As a not logged in user, open https://conditional-tokens-explorer.dev.gnosisdev.com/#/split

**AR:** Amount field is enabled to a not logged in user. However, it becomes disabled when switch to the Split Position option. Or open the Merge potions page. 

**ER:** common logic should be used on all the app pages --> the 'Amount' field should be disabled when a user is not logged in.

**Comment by gabitoesmiapodo** [comment]
I think that in fact it should be enabled in both, as IIRC the user will be asked to connect when clicking the "Split" button?

I they can't complete the form, they can't click the button.

**Comment by gabitoesmiapodo** [comment]
I stand corrected: it's impossible to correctly fill the form when not connected (you won't have funds anyways, and the form will always ask to unlock the collateral, which will ask the user to connect too...), so this is a valid point.

**Comment by elena-zh** [comment]
Verified. 
Also, it would be nice to user 'Not Connected To Wallet' entry for a not logged in user on the Merge Positions page. I have created a low priority enhancement for this case  #375
