### ISSUE TITLE
[FE] - Prepare Omen condition (logic)

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#304]
Prepare an Omen condition (enter Realitio params instead of the raw bytes of a questionId)

**Design:** https://zpl.io/b6rN5Ry
**Wireframes:** https://wireframepro.mockflow.com/view/M6eaccdb4e3776bf4fd576d04b0095a191590507310129#/page/D0f4574597f6c5880ceafbb9909103580

Have this in mind when implementing it: https://github.com/gnosis/conditional-tokens-explorer/issues/343

**Comment by elena-zh** [comment]
Verified. 
The list of the issues, related to this functionality, is created: 
#428, #429, #430, #432, #433, #434, #435, #436
