### ISSUE TITLE
[UX/UI] Positions list/details: Disable 'Redeem' / 'Split' action button when ERC1155 balance is 0.00

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#316]
- Disable the 'Redeem' action button when ERC1155 balance is 0.00 for a position on the Positions list / Position details pages
- Disable the 'Redeem' button for a not logged in user. 
- Also, it would be nice to disable the 'Split' button from a Position details page when ERC1155 balance is 0.00 for a position, and when a user is not logged in.

**Comment by gabitoesmiapodo** [comment]
I'd propose to disable the dropdown's items instead of hiding it.

It's a little confusing when things show sometimes, and sometimes they don't. User is usually clueless about why.

By disabling the items the user could at least infer that something's going on.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I do agree. 
However, we need to apply a common logic to all the action buttons. 
Currently, Wrap/Unwrap/Transfer outcomes tokens buttons are hidden when a token's balance is 0.00. 
So, if we take a decision to disable the buttons (not to hide), we should apply this logic to the action buttons mentioned above.

**Comment by gabitoesmiapodo** [comment]
@elena-zh Sure, we'll probably have to change that too.

**Comment by elena-zh** [comment]
Verified. 
Only one option remains to be hidden - Report payout for a Resolved condition. 
I have added a comment to disable it (not to hide) in #458
