### ISSUE TITLE
Incorrect design of the error message when reject a transaction on the Split positions/Merge positions pages

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#320]
**Steps:** 
on the Split positions page, fill in all the required fields, press on the Split button, then click on the 'Reject' action in Metamask

on the Merge positions page, fill in all the required fields, press on the Merge button, then click on the 'Reject' action in Metamask

**AR:** error message appears, however, the button is in blue. Button is 'OK'
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/bc639a57-04fe-4e19-88eb-273952d1eaf2)

**ER:** button should be in red. Button name = 'Close' like here:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2291e7d3-cab9-4879-ad79-d3c240c99080)

**Comment by gabitoesmiapodo** [comment]
I unknowingly created a similar (but more global) issue here https://github.com/gnosis/conditional-tokens-explorer/issues/342

This and other problems should be fixed there.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , then I'm closing the current ticket.
