### ISSUE TITLE
[UI/UX] Add "Clear" icon to search field

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#325]
Add an icon / button to the search field to allow easily to clear the field.

**Design:** https://zpl.io/bLeQgwm

**Comment by elena-zh** [comment]
@gabitoesmiapodo , just a slight enhancement proposal (if you have a spare time): could you please disable this cross icon when a field is empty (there is nothing to clear out in the field when it is already empty)?
