### ISSUE TITLE
[FE] Update Terms & Conditions, Privacy and Cookie Policy

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#329]
**Cookie Policy:** https://docs.google.com/document/d/1vwv5Xc0G4rQ6_KjcAqbfTzOO2OpyMMRUaZrf5_t6zv4/edit?ts=5fb66078

**Terms & Conditions:** https://docs.google.com/document/d/1P2J8-ALzVkNzAuV4zff1VWmjxjcEE8v536-q2d4w3dE/edit?ts=5fb58d81

**Privacy Policy:** https://docs.google.com/document/d/1MSavws-JgNuqGn_p7aQQEQKnJg6Jy4H_eR44zIIADeA/edit#heading=h.gjdgxs

**Comment by gabitoesmiapodo** [comment]
@cmalfesi could you look into this?

**Comment by cmalfesi** [comment]
@auryn-macmillan I assign this issue to you. Let us know when you have these texts and then you can assign it to me again or to any developer. Thx!

**Comment by cmalfesi** [comment]
Here send you the links of the docs provided by Auryn:

### Terms
https://docs.google.com/document/d/1P2J8-ALzVkNzAuV4zff1VWmjxjcEE8v536-q2d4w3dE/edit?ts=5fb58d81


### Privacy Policy
https://docs.google.com/document/d/1MSavws-JgNuqGn_p7aQQEQKnJg6Jy4H_eR44zIIADeA/edit?usp=sharing



### Cookies Policy
https://docs.google.com/document/d/1vwv5Xc0G4rQ6_KjcAqbfTzOO2OpyMMRUaZrf5_t6zv4/edit?usp=sharing

**Comment by elena-zh** [comment]
Verified. Some minor UI issues are found: #671, #672
