### ISSUE TITLE
[UI/UX] Mobile version: UI issues to fix and discuss

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#330]
Related to #150, #323

1. Android: when try to drag and drop outcomes on  the Edit partition pop-up, white circles appear in the place of the 'moved' outcome. And it is not displayed in the line where it is dropped. Can we fix it?
![edit part - drag and drop.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/82355bc3-ba76-45de-9d63-11e60791f67d)

2.  Placeholders do not fit fields' width on the 'Prepare condition' page (Outcomes field) and on the Transfer outcomes tokens pop-up (Send to field). Can we make placeholder's font size smaller?
![placeholder.JPEG](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5331b814-c8b4-47dd-8bec-eaf192e7dd5c)

![condition - placeholder.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d8e9bfd7-209d-4c3a-98e3-418f3c1570fd)

3. Positions/Conditions page: user needs to scroll down the list first, and then he/she will be able to scroll it to the right. Can we allow a user to scroll grips to the right without scrolling down?
![scroll.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e9cb4bc5-a251-4f04-b24a-41dcfe9cdc35)

4. When open the links in the footer, the pages are not 'auto-scrolled' to the top. A user has to do it manually. 
![scroll to top.JPEG](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1494b392-23a5-47c2-9738-f703a8eb8273)

5. When Select position/select condition pop-up is opened, user is not able to 'tap' on a grid line and select a position/condition. User has to scroll to the right and then press on the Plus icon. Should we leave it as it is, or it would be better to allow a user to select a position/condition using 'tap' action? 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fb25f12c-5e8f-4c4d-8e3f-e4ce48c8478e)

6. Move the filter toggle to the left
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a7514166-aef6-43d7-a755-aa295526fd3e)

7. A bit more technical question. User is able to connect the app with Metamask (if the app is installed) in a mobile device. However, when a user tries to complete any transaction, he/she is redirected to the Metamask, but there is no any confirmation pop-up displayed. So, currently it is impossible to complete a transaction as there is no possibility to confirm the transaction. 
Can we implement such a possibility to call the confirmation pop-up in the mobile app (Metamask)?

**Comment by gabitoesmiapodo** [comment]
App is not intended for mobile use, so I'm closing this for now.
