### ISSUE TITLE
[FE] Merge Positions Results

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#332]
From https://github.com/gnosis/conditional-tokens-explorer/pull/306

It currently looks like this, but it should include the token's icon and ERC1155's decimal point (as seen on Split Position's result).

![Screen Shot 2020-09-24 at 10.22.33.png](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/850d64de-aaae-4f13-9d7d-f9634a2ea68c)

**Comment by elena-zh** [comment]
Verified, 
howerer, one low priority UI issue with pop-up header is found: #360.
