### ISSUE TITLE
[UI/UX] Open links in new window on middle click

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#334]
This is just a personal preference of mine, but I use to open lots of tabs / windows using middle click, and some of the links here don't work that way, specially links for conditions / positions on tables.

Maybe the same for dropdown menus, and table rows?

Main menu and footer's links are fine, BTW.

**Comment by elena-zh** [comment]
Verified. 
However, I have found an issue with opening a condition details from a position details page. I have created a separate ticket for this issue #387
