### ISSUE TITLE
[FE - UI/UX] Additional search items

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#337]
In both the "conditions" and "positions" tabs, along with "select position" modal in the "split position" and "merge position" tabs, you have only one type of input to search by; condition ID or position ID. Most other interfaces wont expose these IDs to users, so someone coming from another interface (say Omen) will have a really hard time tracking down the corresponding condition/position.

Contrast this to search on something like Etherscan, where you can enter address, txhash, ens name, token name, block number, contract name, etc.

We should allow users to search by:
1. condition ID
2. position ID
3. question ID
4. oracle address
5. question text (for Reality.eth or similar conditions)
6. eth address (and ENS name, maybe?) condition creators and position holders
8. other things, maybe?

**Comment by gabitoesmiapodo** [comment]
This will addressed on https://github.com/gnosis/conditional-tokens-explorer/issues/403 (epic)

Also @auryn-macmillan, there are some questions for you in https://github.com/gnosis/conditional-tokens-explorer/issues/409 and https://github.com/gnosis/conditional-tokens-explorer/issues/414
