### ISSUE TITLE
[FE] Display message for conditions yet to be indexed

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#338]
When the user tries to get into the "Condition Details" section and it hasn't been indexed yet by the subgraph, they will get an "Error / Condition Not Valid" message, which is confusing (and kind of wrong).

So, we could show a more descriptive message telling them what's going on.

Workflow:

1. User tries go the to the Condition Details section for an unindexed condition (this could be from the Conditions List section, or after a successful "Prepare Condition" transaction).
2. Using a "FullLoading" component, show the following:

- Title: Condition Details.
- Icon: Spinner.
- Message: “Transaction successfully finished, now waiting for the condition to be indexed. Check again in a few minutes.“
- Button: Green "OK" button, which redirects to the Conditions List on click.

**Comment by elena-zh** [comment]
Verified. 
User is redirected to the Positions list when he/she clicks on the Ok button on the modal - #383
