### ISSUE TITLE
[FE - UI/UX] Add more filters to conditions and positions tab

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#341]
In the conditions tab, we should be able to filter by:
- Oracle: should be able to select oracles like "Custom", "Reality.eth", etc, or enter an ethereum address / ENS name
- Validity: similar to how you can filter for valid markets on Omen
- Number of outcomes
- Question ID
- Creation date
- Total Value Locked

In the positions tab, we should be able to filter by:
- Creation date
- Oracle: should be able to select oracles like "Custom", "Reality.eth", etc, or enter an ethereum address / ENS name
- Validity: similar to how you can filter for valid markets on Omen
- Total Value Locked
- Token (select from known tokens or enter an address)
- Condition ID
- Question ID

**Comment by gabitoesmiapodo** [comment]
This looks like a high priority one from a UX standpoint.

I'm assigning this to me and Mariano so we can add some more info to this (design and implementation).

**Comment by gabitoesmiapodo** [comment]
@auryn-macmillan It seems some of these are overlapping with the search feature in 

I’m going to work on the design, adding a new “advanced filters” feature, which will only include the following (some of these will depend if it’s for Positions or Conditions).

This is more or less what I'm thinking I'm going to do:

**Basic filters**

- Oracle.
- Collateral.

**Advanced filters**

- Validity (I'm not certain about what validity is?)
- Number of outcomes (should this be a range? or max outcomes?)
- Creation date (from / to range?)
- Total Value Locked (should this be a range or an exact value?)

The rest would go to the search feature, which could be end up including (it will vary depending if it's for the conditions or position's list):

- Condition ID.
- Position ID.
- Question ID.
- Oracle Address.
- Question text (for Reality.eth or similar conditions).
- ETH Address.
- ENS name.
- Condition creator (I think this is a custom oracle / reporter?).
- Position holders.
- Token Address (which would allow to search custom tokens).

**Comment by auryn-macmillan** [comment]
For the fields that you had questions on, these are my suggestions.

**Advanced filters**

**Validity**: this is based on Omen and may not be relevant on the explorer. But I think the information is in the subgraph.
**Number of outcomes**: this should be a range
**Creation date** this should be a  from-to range
**Total Value Locked**: this should be a range

**Search feature**

**Condition creator**: this is just the address who created the condition

**Comment by gabitoesmiapodo** [comment]
@auryn-macmillan Great, thank you!

**Comment by gabitoesmiapodo** [comment]
This will addressed on https://github.com/gnosis/conditional-tokens-explorer/issues/404 (epic)

Also @auryn-macmillan, there are some questions for you in https://github.com/gnosis/conditional-tokens-explorer/issues/412
