### ISSUE TITLE
[FE] Status Info consistency issues

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#342]
While we are correctly informing _most_ of the transactions' statuses, we should make them more consistent.

1. For instance, on "Prepare Condition", complete the form, click on "Prepare", and reject the transaction in Metamask. This is the result:

![Screen Shot 2020-09-24 at 15 27 55](https://user-images.githubusercontent.com/4015436/94185936-65783d00-fe7c-11ea-80a9-16835ee4f202.png)

That shouldn't be the case. Show a proper "Error" `FullLoading` component (see screenshot in next item).

**Title:** Error.
**Icon:** Error icon.
**Text:** Same text as in the screenshot.
**Button:** Red "Close" button.

2. For "Split Position", complete the form, click on "Split", and reject the transaction in Metamask. This is the result:

![Screen Shot 2020-09-24 at 15 28 30](https://user-images.githubusercontent.com/4015436/94186151-b25c1380-fe7c-11ea-83c5-d9bab7df49bb.png)

This is mostly OK, but anyways:

**Title:** Error.
**Icon:** Error icon.
**Text:** Same text as in the screenshot.
**Button:** Red "Close" button.

Also modal's width should be narrower (see screenshot in item `#3`, it should look like it).

3. For "Merge Positions", complete the form, click on "Merge", and reject the transaction in Metamask. This is the result:

![Screen Shot 2020-09-24 at 15 30 34](https://user-images.githubusercontent.com/4015436/94186761-77a6ab00-fe7d-11ea-8140-55dab930796e.png)

It's OK, but the button should be red.

**Title:** Error.
**Icon:** Error icon.
**Text:** Same text as in the screenshot.
**Button:** Red "Close" button.

4. For "Redeem Positions", complete the form, click on "Redeem", and reject the transaction in Metamask. This is the result:

![Screen Shot 2020-09-24 at 15 33 30](https://user-images.githubusercontent.com/4015436/94186930-a886e000-fe7d-11ea-8792-612015d160ef.png)

It's OK, but the button should be red.

**Title:** Error.
**Icon:** Error icon.
**Text:** Same text as in the screenshot.
**Button:** Red "Close" button.

5. For "Report Payouts", complete the form, click on "Report", and reject the transaction in Metamask. This is the result:

Nothing. There's no error.

So, implement this:

**Title:** Error.
**Icon:** Error icon.
**Text:** Meaningful text.
**Button:** Red "Close" button.

**Comment by elena-zh** [comment]
Verified. 
Looks good to me. 
However, it would be nice to adjust the modal width for the rest the same modals in the app. Descrived in #454
