### ISSUE TITLE
[FE] Categories don't match Omen

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#343]
The categories in the dropdown when you create an Omen condition do not match those on Omen.

![image](https://user-images.githubusercontent.com/8453294/94188292-2a273f80-fe77-11ea-8f2c-badd714e8174.png)

![image](https://user-images.githubusercontent.com/8453294/94188322-34e1d480-fe77-11ea-92dc-18cfd3e9f2fc.png)

**Comment by gabitoesmiapodo** [comment]
This should be implemented here https://github.com/gnosis/conditional-tokens-explorer/issues/304 but I'll reference this issue so we don't forget.
