### ISSUE TITLE
[FE] Add "Condition ID" to Position Details and more...

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#344]
- We think it'd be useful to have the related condition id available in the Position Details. It should be a link to "Condition Details" and also have the copy to clipboard button.
- Change "Outcomes Collections" to "Collections" below "Partition"
- Change "Position" to "Position Preview" at the bottom.

Design, in case you need it: https://zpl.io/2GZznJ9

**Comment by elena-zh** [comment]
@gabitoesmiapodo , @mariano-aguero ,

I have verified the issue. 
My question is related to the Condition IDs section: as far as I understand, a position can have only one condition ID (and vise versa, one condition ID can have a lot of positions IDS). Hence, why should we display the condition id as a grid on the position details page? 
![condition](https://user-images.githubusercontent.com/70885163/94557192-e8c3d500-0266-11eb-8181-0f497ba4ae2e.jpg)

From my perspective, it would be nice to display it as a line (like CONTRACT ADDRESS or so). 

What do you think about it?

**Comment by gabitoesmiapodo** [comment]
@elena-zh It seems there can be more than one condition for a position, although it's rare (I have personally never seen it).

There's a related issue here https://github.com/gnosis/conditional-tokens-explorer/issues/379

**Comment by elena-zh** [comment]
@gabitoesmiapodo , thanks a lot.
