### ISSUE TITLE
Cannot prepare Omen condition

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#345]
After filling out all of the fields to prepare on Omen condition, pressing the "prepare" button does not initiate a transaction in Metamask.

![Screen record from 2020-09-24 15 19 19](https://user-images.githubusercontent.com/8453294/94189916-5fcd2800-fe79-11ea-9e8a-056cdaf58f1c.gif)

This works as expected with a custom reporter.

**Comment by gabitoesmiapodo** [comment]
This will be implemented here: https://github.com/gnosis/conditional-tokens-explorer/issues/304

**Comment by auryn-macmillan** [comment]
Cool, I'll close this issue then.
