### ISSUE TITLE
Drag outcomes into empty space to make new partition

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#348]
You can drag and drop outcomes between collections, but not into empty space.
This means that if you want to place an outcome that is currently in a collection outside of the current collections, you have to delete the collection it is in and create two new collections.

![Screen record from 2020-09-24 15 34 13](https://user-images.githubusercontent.com/8453294/94191389-6fe60700-fe7b-11ea-8a9e-f5d1cd016aa4.gif)

**Comment by gabitoesmiapodo** [comment]
Duplicate of https://github.com/gnosis/conditional-tokens-explorer/issues/278

**Comment by auryn-macmillan** [comment]
Thanks! I'll close this one.
