### ISSUE TITLE
[FE] Display Condition ID once required fields are filled

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#350]
When creating a condition, we can know what the condition ID is as soon as the question ID, outcomes, and reporting address have been filled.

We should:
1. display the resulting ID
2. Disable the prepare button if the condition already exists
3. Provide a link to the condition if it already exists

**Comment by elena-zh** [comment]
Verified. 
Comment is [here](https://github.com/gnosis/conditional-tokens-explorer/pull/498#issuecomment-716409376)
