### ISSUE TITLE
[FE] We should come up with some reasonable naming convention for wrapped outcome tokens

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#352]
Right now, when you wrap an outcome token, it is labelled "WMT".

![image](https://user-images.githubusercontent.com/8453294/94193422-55f9f380-fe7e-11ea-9aa0-bf06e74368bb.png)

What does that mean?

We should come up with a naming convention for these tokens.

Something like `Wrapped [DAI C:0xba11...501d O:0]` probably makes sense.

**Comment by mariano-aguero** [comment]
> Right now, when you wrap an outcome token, it is labelled "WMT".
> 
> ![image](https://user-images.githubusercontent.com/8453294/94193422-55f9f380-fe7e-11ea-9aa0-bf06e74368bb.png)
> 
> What does that mean?
> 
> We should come up with a naming convention for these tokens.
> 
> Something like `Wrapped [DAI C:0xba11...501d O:0]` probably makes sense.

Mmm this is the symbol returned for the ERC20 wrapped contract, I don't know what it means, maybe something like ```Wrapped M... Token```

**Comment by auryn-macmillan** [comment]
@cag does so every wrapped outcome token has the same symbol and name?
That seems less than ideal.
The symbol may be unavoidable, since I don't think there is enough room to do anything meaningful. (is there actually a character restriction?)
But the name could be much more meaningful.

**Comment by auryn-macmillan** [comment]
I guess it's probably because this is meant to be a generic 1155 wrapper, not specific to conditional tokens.

**Comment by mariano-aguero** [comment]
This is an image of the WMT ... 
![Uploading Screenshot_20200924_172513.png…]()

**Comment by mariano-aguero** [comment]
> I guess it's probably because this is meant to be a generic 1155 wrapper, not specific to conditional tokens.

Mmm probably, but you're right we have to do something about it

**Comment by gabitoesmiapodo** [comment]
Maybe we could add a more descriptive tooltip to the symbol.

**Comment by mariano-aguero** [comment]
> Maybe we could add a more descriptive tooltip to the symbol.

Maybe, we can add the name as a tooltip `Wrapped ERC-1155` ?

**Comment by cag** [comment]
> @cag does so every wrapped outcome token has the same symbol and name?

Yeah. There's no character restriction though I would shy away from long symbols as that might break interfaces. `WMT` stands for Wrapped Multi Token. I have it to be the same across the board because I didn't want to write more deployment logic that's already a bit error prone in assembly. As for the name, there's not an easy way on-chain to get a sensible name for any given Wrapped1155 token, and keeping the deploy bytecode relatively simple was kind of a goal for me, so the trade off is the symbol and the name is stuck being something kind of generic.

**Comment by auryn-macmillan** [comment]
That's all fair enough. I'm happy to leave it like that, but it will make interacting with these tokens on things like uniswap very confusing.
i.e. if I were to set up a market between two wrapped tokens, they will both have the same name and symbol.

If we can't create a reasonable naming convention, perhaps a randomly generated name / symbol would be preferable? Just so they are distinguishable in UIs that don't have any context on what the token is.

**Comment by elena-zh** [comment]
Verified. 
Etherscan's link is added for "Collateral Address".
Tooltip for "WMT" is added.
"Wrapped Collateral Address" section is added to the details. User can copy the address, or just open Wrapped Collateral Address details in Etherscan.
