### ISSUE TITLE
[UI/UX] Link to Omen markets, where relevant

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#356]
From the condition details view, and potentially from other places in the app, we should be able to expose any omen markets that have been created for a position and link out to them.

**Comment by mariano-aguero** [comment]
This is possible bad estimated, we need designs here. Is a task that will take a long time to be implemented

**Comment by cmalfesi** [comment]
After a chat with Auryn, we can give this issue a high priority.
@gabitoesmiapodo please, start to draw some designs regarding this feature when you can. Thx!

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero @cmalfesi I think this could be implemented with what we already have. Something like this:

![Screen Shot 2020-11-05 at 09 40 08](https://user-images.githubusercontent.com/4015436/98243767-2e05b180-1f4d-11eb-83de-351cb5eeac33.png)
![Screen Shot 2020-11-05 at 09 41 22](https://user-images.githubusercontent.com/4015436/98243771-30680b80-1f4d-11eb-9cb1-a1460bb6d0c3.png)
![Screen Shot 2020-11-05 at 09 47 15](https://user-images.githubusercontent.com/4015436/98243773-3100a200-1f4d-11eb-851a-ad70e633b120.png)
![Screen Shot 2020-11-05 at 09 52 06](https://user-images.githubusercontent.com/4015436/98243774-3231cf00-1f4d-11eb-8982-e163641e1005.png)

It's simple enough that it could be added anywhere in the app.

Anyway, with the growing amount of information for the details sections we may need to rethink some of the layouts and data hierarchy in the future (probably not yet, though).

**Comment by mariano-aguero** [comment]
> @mariano-aguero @cmalfesi I think this could be implemented with what we already have. Something like this:
> 
> ![Screen Shot 2020-11-05 at 09 40 08](https://user-images.githubusercontent.com/4015436/98243767-2e05b180-1f4d-11eb-83de-351cb5eeac33.png)
> ![Screen Shot 2020-11-05 at 09 41 22](https://user-images.githubusercontent.com/4015436/98243771-30680b80-1f4d-11eb-9cb1-a1460bb6d0c3.png)
> ![Screen Shot 2020-11-05 at 09 47 15](https://user-images.githubusercontent.com/4015436/98243773-3100a200-1f4d-11eb-851a-ad70e633b120.png)
> ![Screen Shot 2020-11-05 at 09 52 06](https://user-images.githubusercontent.com/4015436/98243774-3231cf00-1f4d-11eb-8982-e163641e1005.png)
> 
> It's simple enough that it could be added anywhere in the app.
> 
> Anyway, with the growing amount of information for the details sections we may need to rethink some of the layouts and data hierarchy in the future (probably not yet, though).

I'm ok with this implementation, is a start
