### ISSUE TITLE
[FE] Find matches for incomplete search terms

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#359]
Right now, we only find exact matches.
We should also return matches for incomplete search terms.

e.g. `0x` should return all.

![Screen record from 2020-09-24 16 52 59](https://user-images.githubusercontent.com/8453294/94199314-9e1d1400-fe86-11ea-9662-181b7250e4fd.gif)

**Comment by elena-zh** [comment]
Verified. 
Now the app returns matches for incomplete search terms on  Positions and Conditions lists. 
Some notes and related issues  are listed [here](https://github.com/gnosis/conditional-tokens-explorer/pull/508#issuecomment-717280800)
