### ISSUE TITLE
[FE] Balance of a position is not cleared out after a merge

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#365]
Here is the description: 
**Condition:** 0xa21d0f0f0cfb53b3ca9a70fdae20be0888c9c6058a93df050e483d08d181904a
	1 position 0x0f601160e4bc2506b847a4eceab8931ddfdb1a36a24ca91f4fd7b4f4a649d6aa with 1 balance
	2 position 0x57410364a7b9ac15b6b980492b4e1aa761923dd3fbd156eb1e4a3643841db29f with 1 balance
	3 position 0xb5b259c452a194ecad208d49c05994d4c5b0f915b5f7cf63f7d5f6ac71a92019	with 1 balance, but after position split it has  0 balance
	
**the 3rd position**  is splitted to: 
	3.1 - 0xffbb5a10865dc9d374e75216199d5290cb81beb39b6fdc7516e2e809c4b71f37 - 1  -merged 
	3.2. -  0x0b2217c5a22f563d63bd4d15ac916b703e8dda2f93289e16c805c90fd4a242dd - 1 - merged
	3.3. -  0xe4ff4f272dde48ca025e085b761c4d75831d3be92fb8b468ce863cabf0653f03 - 0 (has 0 balance after split? #289)
	
**Positions 3.1 and 3.2. were merged** into the 0x0bbd02179644019371e8a5afc6ff5be333e466285a1b52f7322bd6a81ef0db70 . It has 1 balance
	
However, **positions 3.1 and 3.2.** still have the balance =1. 

**Expected result:** positions 3.1 and 3.2. should have the balance =0,00 after a merge?

**Comment by hpmaxi** [comment]
This is related with #328 . Maybe we could close that one because this has a better description.

**Comment by elena-zh** [comment]
@hpmaxi , these are a bit different issues. 
#328 is related to the positions displaying on the positions list (and that we need to update the page and then see. that the balance is changed)

The current one describes the situation that the balance is not updated even after a page update. It remains the same after the merge.

**Comment by hpmaxi** [comment]
> @hpmaxi , these are a bit different issues.
> #328 is related to the positions displaying on the positions list (and that we need to update the page and then see. that the balance is changed)
> 
> The current one describes the situation that the balance is not updated even after a page update. It remains the same after the merge.

@elena-zh Sorry, my fault. I got confused with another one that I created, #289, and the duplicated one that is closed.

**Comment by elena-zh** [comment]
Seems to be unfixed: **See the pic**
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/5aa9cd7d-92ef-458d-adfd-78eb4c0cd994)

positions 3.1 and 3.2. still have a positive balance, and it is never cleared out even if I redeem positions several times. 
Also, a new weird thing started to be reproducible: when I merge positions 3.1 and 3.2., balances for the Position 1 and Position 2 become zero (however, nothing should happen with them). 

@hpmaxi , could you please take a look into the issue once again?

**Comment by hpmaxi** [comment]
This needs further research but the reason that we're not burning deeper positions into shallower ones seems to be related to the parentCollection calculation and how we read the indexSet from the graph. The position with only one element in indexSets is always shown as a level 1 position, and therefore incompatible for merging with the level 2 positions, and also the ordering in the array seems to be important in calculating the resulting indexSet.

Splitting `0x3775c8db8b860b86cab45d05463ab8a966f5e8d1aa81972b4dc3e4752b9223ad` (a deeper position of indexset: 4) with condition `0xc8874a83f4e2c6930c0c1f5fcc2211445bb889777c5505345c50b3dc19bbe2d1` results in

```
0xc6890ea9a7c5f4d8fc40ea5910830fc8b7b295d7c46a6fc5285028350b303803 =>   [1 4]
0x833dde0cb0377ac9e1c26149f26b4508c4aab1d6fa4fa091038948c9ca267a56 =>  [4 2]
0x90e09f2cfce3ee147d51dbe54d92387668ad205997ff82a946a15ac138ee1501 =>  [4]
```
The last one, from thegraph side, is shallower. 

If I'm not wrong, merging the first two should result in a position of indexSet [3 4], but instead it generates a position of indexSet 5, and shallower too. 

```
{
  position(id: "0x95477aa1a5347f1ce5262f85d540ff9a484f6a71183dccf586993aafd99b4e46") {
    id
    indexSets
    conditionIds
  }
}
```

**Comment by elena-zh** [comment]
I have rechecked the issue. 
Now  a user is not allowed to merge positions of a 'deeper' level. 
Also, the issue mightn't be relevant after #512 is implemented (as a user should see only mergeable positions). 
I'm closing the bug for now.
