### ISSUE TITLE
[FE] Improve context to avoid race conditions handling inside consumer components

### ISSUE THREAD

**Issue by hpmaxi** [gnosis/conditional-tokens-explorer#373]
Currently we have a few contexts, one of them is `MultiPositionsContext` which exposes functions to modify a list of `positionsIds` but also a list of positions fetched from the subgraph along with his ids in another variable, so it is possible to use two versions of the same thing without having one being a transformation of the other.

For example, if we consume `positionsIds` AND positions we have to check that both are in sync, because positions are fetched asynchronously, they could have the same length but positions still have the "full" version of some point earlier in the execution. 

In my opinion, a solution is to expose only one list (the positions full object list) if it is completely necessary to have the list of ids then calculate it with `map` in each component. 

We should leverage existing hooks and compose more of them, in this case `usePositions` could be used inside of `MultiPositionsContext` instead of a custom query to avoid code duplication but also to free `SelectPositions` component of the responsibility of fetching the balance. And maybe I'm missing something but It could be that `BatchBalanceContext` could be removed, so with all this I think hardly ever we would deal with race conditions related to positions balances and positions selections.

**Comment by mariano-aguero** [comment]
It's not necessary because new designs
