### ISSUE TITLE
[FE] Storage item race condition for auto-filled fields

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#378]
Related to #377

Dropdown items like "Redeem", "Split Positions", "Merge Positions", etc. are links but at the same should auto complete some fields in the target form. This works well with regular left clicks (open link in the same window), but it doesn't work so well when using middle click to open multiple tabs.

**For example:**

- Go to any condition's details page.
- Open the top right dropdown.
- Always using middle click open "Split Position", "Merge Positions", and "Report Payouts".
- Check the opened tabs, and you'll see that only one (or maybe none) of the tabs has the pre-filled fields correctly pre-filled. 

This is because there's a unique identifier for the storage item used to transfer data, and that storage item is deleted when the section loads, making it unavailable for the other tabs.

We should fix this and all forms should be pre-filled as expected.

**Update 19/11/2020:**

@hpmaxi The latest changes to the condition and position selection are already in place. That means that part of this functionality (auto filling conditions / positions) could be broken. Please have that in mind when addressing this and fix everything you find. Also https://github.com/gnosis/conditional-tokens-explorer/issues/378#issuecomment-729901163

**Comment by gabitoesmiapodo** [comment]
We should leave this untouched until #510 is done.

**Comment by gabitoesmiapodo** [comment]
@hpmaxi just so we don't forget, there are several issues mentioning issues related to this:

https://github.com/gnosis/conditional-tokens-explorer/issues/640
https://github.com/gnosis/conditional-tokens-explorer/issues/639
https://github.com/gnosis/conditional-tokens-explorer/issues/637

**Comment by elena-zh** [comment]
Cases #637 and #640 are fixed in #583
