### ISSUE TITLE
Resolution date for Omen conditions is incorrect

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#392]
All Omen conditions show a resolution date of `1970-01-01 - 00:00 UTC`.
![image](https://user-images.githubusercontent.com/8453294/94703886-5296ba00-030d-11eb-902d-5faef8dfaae6.png)

**Comment by elena-zh** [comment]
According to the discussion in #443, resolution date is removed from an opened condition. 
It should be displayed when a condition is resolved. For now, I do not have such a possibility tj check it as there is no any resolved omen condition in CTEAF. I have created an issue for this case and will check the resolution date once the #466 issue is fixed.
