### ISSUE TITLE
Select positions list is blinking when search for a position

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#396]
See the video: 
https://drive.google.com/file/d/1loB6JJdxNP6ZV3f96hbb-g9kuoAhbFGH/view
each time when I run a search (partial or for a positions which do not exist in the list), positions grid is blinking for a moment then returns no results. 

**Expected Result:** no blink before the no results screen

**Comment by gabitoesmiapodo** [comment]
This was fixed elsewhere, and also select modals are no more.
