### ISSUE TITLE
[FE] Condition List Search Items (Needs confirmation / research)

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#409]
Related to #408 

We need to check if it's possible to implement these search options, or what changes are needed to implement them:

- Position Id (should show all related conditions?)
- Question Text (for Omen Conditions).
- ETH Address (what does this mean?)
- ENS Name, probably we could do it if we first resolve the ENS name, and then search by ETH address.
- Validity

**Design:** https://zpl.io/awKqdB1 - https://zpl.io/VDLZ6lr

**Comment by mariano-aguero** [comment]
We will only implement the search by:
- Position Id (should show all related conditions?)
- Question Text (for Omen Conditions)
- ENS Name, probably we could do it if we first resolve the ENS name, and then search by ETH address.

**Comment by mariano-aguero** [comment]
Blocked by https://github.com/gnosis/hg-subgraph/issues/32

**Comment by mariano-aguero** [comment]
This probably will change with the new design, after that we will analyze what to do.

**Comment by gabitoesmiapodo** [comment]
Outdated (new design includes a new search bar), closing.
