### ISSUE TITLE
[FE] Conditions List Filters

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#410]
Related to https://github.com/gnosis/conditional-tokens-explorer/issues/337 and https://github.com/gnosis/conditional-tokens-explorer/issues/341#issuecomment-700259206

**Design:** https://zpl.io/awKqdB1 - https://zpl.io/VDLZ6lr

The user should be able to filter by:

- Reporter / Oracle: All / Current Wallet / Custom Reporters / Realit.io / Kleros
- Status: All / Open / Resolved
- Condition Type: All / Custom Reporter / Omen Condition
- Number of Outcomes: A min / max range.
- Creation Date: A from / to range.
- Validity: All / Valid / Invalid (this is for Omen Conditions, check https://omen.eth.link/rules.pdf)

Hiding the filters' column should clear the filters.

**Comment by elena-zh** [comment]
Works fine.
Some notes: Validity option is removed from the filter options for now (see comments in #443).
2 related issues are created: #468, #469. 
Also, several issues remain to be unfixed in #440.
