### ISSUE TITLE
[FE] Positions List Filters

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#411]
Related to https://github.com/gnosis/conditional-tokens-explorer/issues/337 and https://github.com/gnosis/conditional-tokens-explorer/issues/341#issuecomment-700259206

**Design:** https://zpl.io/bLeQgwm - https://zpl.io/2ENrpny

- Collateral: All / DAI / USDC / cDAI / WETH / OWL / GNO / Custom Token.
- Wrapped Collateral: All / Yes / No - (_Yes_ meaning "It has wrapped collateral" and _No_ meaning that it hasn't).
- Creation Date.

Hiding the filters' column should clear the filters.

**Comment by elena-zh** [comment]
Verified. 
The notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/497#issuecomment-715289418)
