### ISSUE TITLE
[FE] Positions List Filters (Needs confirmation / research)

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#412]
Related to #411

We need to check if it's possible to implement this filter, or what changes are needed to implement it:

- Total value locked: A min / max range.

**Comment by auryn-macmillan** [comment]
Yeah, I guess this probably is not available on the sugbraph.
It would be possible to compute it client-side, but I don't think we want to do that.

Perhaps we scrap TVL.
