### ISSUE TITLE
[FE] Positions List Search Items

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#413]
Related to https://github.com/gnosis/conditional-tokens-explorer/issues/337 and https://github.com/gnosis/conditional-tokens-explorer/issues/341#issuecomment-700259206

Design: https://zpl.io/bLeQgwm - https://zpl.io/2ENrpny

- All (includes all of the next items).
- Position Id.
- Condition Id.
- Collateral Symbol (Only for the tokens in the default configuration).
- Collateral Address (we should update "Contract Address" in the position's details section to use the same wording).
- Token Address.

Placeholder text should change according to the selected option.

**Comment by elena-zh** [comment]
Verified. 
The notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/497#issuecomment-715289418)
