### ISSUE TITLE
[FE] Positions List Search Items (Needs confirmation / research)

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#414]
We need to check if it is possible to implement these search options, or what changes are needed to implement them:

- Position Holders.
- ETH Address: what does this mean?
- ENS Name: we can do it only if we first resolve the ENS name, and then search by ETH address.
- Question Id. 
- Question text (for Omen conditions).

Related to #413

**Comment by mariano-aguero** [comment]
We will be able to search by ENS Name if the subgraph implement the field creator for the position entity.
The other fields are discarded.

**Comment by mariano-aguero** [comment]
This probably will change with the new design, after that we will analyze what to do.

**Comment by gabitoesmiapodo** [comment]
Outdated (new design includes a new search bar), closing.
