### ISSUE TITLE
[FE] - Naming convention and folder structure

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#42]
- Apply a naming convention for folders and files
- Try to use a real component name instead of index.tsx (this helps to identify easily the component in the editor) ?
- create `component` folder and include general components inside
- Organize the `pages` folder better (most important)
- utils, constants, theme?
- Improve in general all names that make easier the work later
- Use UpperCamelCase

**Sections**

- [ ] Condition details
- [ ] Condition list
- [ ] Merge positions
- [ ] Position details
- [ ] Position list
- [ ] Prepare condition
- [ ] Redeem positions
- [ ] Report Payouts
- [ ] Split Positions

**Comment by gabitoesmiapodo** [comment]
This is (probably) mostly done.

@mariano-aguero do you have some ideas about what could we be still missing?

**Comment by mariano-aguero** [comment]
> This is (probably) mostly done.
> 
> @mariano-aguero do you have some ideas about what could we be still missing?

We're going to move some folders from the pages sections to the componentes sections. Shall we work on this in the next milestone ? I think yes, Any thoughts ?

**Comment by gabitoesmiapodo** [comment]
I think this should be already done, but we keep not doing it for whatever reasons...

I say you should start working on this ASAP. I don't think there's a huge deal of work left from this issue anyways (we already did some), and we should fix this and forget about it.

@lmcorbalan @hpmaxi @cmalfesi thoughts?

**Comment by gabitoesmiapodo** [comment]
This went into oblivion and it's really outdated (and more or less done), I'm closing it.
