### ISSUE TITLE
Prepare Omen condition: issues with the Resolution date field

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#434]
Related to #415, #304

1. It is allowed to enter a year in the distant future - see the pic
![year.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a36ec2b2-01f8-47ec-8af0-a612efe65e28)

2. System allows to enter a day that does not exist in the not leap year
![not a leap year.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/352524a6-ee22-4200-87ba-9e25451dbf99)

**Expected result:** disable manual input in the field (in Omen, user is allowed to select a date only using a calendar)

**Comment by mariano-aguero** [comment]
Wait to this PR to be closed https://github.com/gnosis/conditional-tokens-explorer/pull/443

**Comment by elena-zh** [comment]
Works fine. Now a user is warned about a date limits and is not allowed to filter conditions lists/create an Omen condition with invalid date. 

However, one trivial UI issue remains to be reproducible on the Prepare Omen condition page: year input  is not limited to 4 digits. 
I have created another ticket #495 for this case to fix it later.
