### ISSUE TITLE
Prepare Omen condition:  System allows to create a condition with the question and outcomes which are already exist

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#435]
I have created exactly the same Omen condition (except the date - the system does not allow to enter a date < than 01-01-1970)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/085ad489-bf4c-41f4-9b4e-0e55b0eab0e2)

And the condition was successfully created: 
https://conditional-tokens-explorer.dev.gnosisdev.com/#/conditions/0x5571136da50dd0ae6f76975d422f67acc801597422342ba94b5a74506856203b

**Expected result:** 
do not allow to create the same questions? 
I'm not sure..

**Comment by mariano-aguero** [comment]
System will  allow to create a condition with the question and outcomes which are already exist, if It was created more than 24 hours ago

**Comment by elena-zh** [comment]
> System will allow to create a condition with the question and outcomes which are already exist, if It was created more than 24 hours ago

I still do not see any warning message, even if I create the same condition with the same outcomes within an hour or 2.
I'd better reopen the issue.

**Comment by mariano-aguero** [comment]
I created a question, this one ,  with date 16/10 
When I tried to create the same question, for the same day, I got the error https://reality.eth.link/app/#!/question/0x612f7b83b2ff3a27a0cf2e718444db7605615f26609a2b762e28e21e67372d04

![Screenshot_20201014_170736](https://user-images.githubusercontent.com/1144028/96040131-2cf6ce00-0e40-11eb-95bc-c46924782869.png)



![Peek 14-10-2020 17-06](https://user-images.githubusercontent.com/1144028/96039913-ce315480-0e3f-11eb-980f-82d565d9373d.gif)

**Comment by elena-zh** [comment]
Finally! it is not reproducible for me. 
However, another issue with Prepare condition form is found - #486
