### ISSUE TITLE
Newly created positions do not appear in the Positions list; position details show 404 error

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#438]
**(!) Newly created conditions do now appear in the Conditions list as well.** 

I have split a condition several times. 
![positions.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/da8f0bc9-6b80-4c3a-b8a7-7a0dc6d07d31)

![the 2nd case.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3bc8eb12-f1bd-443a-8335-a43e91d1439d)

Each time I have a success pop-up, however, when I open a position detail, I wee the 404 message. 
![positions not found.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e780f063-0ba5-44bd-80d1-6f1e83ef0770)

Also, the positions do not appear in the positions list

However, the positions are exist in the Subgraph
![positions exist.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/b50129db-9e41-4656-b861-27d090de690f)

**Comment by gabitoesmiapodo** [comment]
This seems to be related to TheGraph, and it was reported here https://github.com/graphprotocol/graph-node/issues/1934

Actually nothing works right now (except for what was already indexed on the subgraph), so we have to wait until that is fixed...
