### ISSUE TITLE
Position remain to be displayed on the Split position page after the completed split

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#439]
1. Open Split Position page
2. Select split a position
3. Successfully split it
4. Do not move to other app's pages
5. Select Split position tab

**Actual Result:** Position remain to be displayed in the Position field. 'Use Wallet Balance' button displays the position amount
![after split position.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/efdfa09a-6f21-44f4-9e6b-2b662a326c89)

**Expected Result:** Position field is empty. 'Use Wallet Balance' button displays 0.00

**Note**: It would be nice to rename 'Use Wallet Balance' button to 'Use Position Balance' button when split a position

**Comment by gabitoesmiapodo** [comment]
Probably invalid after we merge https://github.com/gnosis/conditional-tokens-explorer/pull/597

(@elena-zh please check it)

**Comment by elena-zh** [comment]
@gabitoesmiapodo , yes, you're right. The issue is invalid in the new design. 
I'm closing the bug. 
Thanks
