### ISSUE TITLE
[FE] Condition List Search Items, improvements for searching in the subgraph

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#447]
We need some fields to be of type string to be able to use the suffix _contains and improve the search in thegraph

Fields:
- conditionId
- questionId
- oracle
- creator

**Comment by mariano-aguero** [comment]
Related issue https://github.com/gnosis/hg-subgraph/issues/23

**Comment by elena-zh** [comment]
Verified. 
Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/508#issuecomment-717280800)
