### ISSUE TITLE
[FE] Edit / Remove outcomes is not working

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#451]
This needs to be done after #443 and #449 are approved and merged.

- Go to "Prepare condition"
- Select "Omen Condition"
- Fill all the fields, do not add outcomes.
- Add three outcomes named "1", "2", and "3".
- Edit the names to "11", "22", "33", you'll see the changes on the screen.
- Click on "Prepare".

After the condition is created, you should see that the outcomes' names are still "1", "2", and "3". So: editing doesn't work.

The same should happen if you remove outcomes.

**Comment by elena-zh** [comment]
Some more cases (as a result of a testing the #433): 
1. Spaces preceding and trailing are still not truncated on editing. 
2. We need to consider how to manage cases with upper- and lowercase letters in the outcomes
![image](https://user-images.githubusercontent.com/70885163/95588474-233e2680-0a4c-11eb-9dd9-68207bb396e2.png)
3. It is still allowed to add the same outcomes  with preceding and trailing spaces. As a result, weird things are happening on a edit/delete outcomes actions: https://drive.google.com/file/d/1iNCv4z7_rYzR5_YCROqyObHZBS7ku3gX/view

**Comment by mariano-aguero** [comment]
> 2\. We need to consider how to manage cases with upper- and lowercase letters in the outcomes

I think we need to consider the existence of both
