### ISSUE TITLE
[FE] Conditions / positions List Search Items for modals

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#452]
Is pretty much the same as the condition list page, but for modals

**Comment by gabitoesmiapodo** [comment]
Wether we implement this or not will depend on https://github.com/gnosis/conditional-tokens-explorer/issues/358#issuecomment-712238025

So let's wait for now.

**Comment by gabitoesmiapodo** [comment]
This will be implemented on https://github.com/gnosis/conditional-tokens-explorer/pull/571
