### ISSUE TITLE
Number of positions on the Conditions/Positions list got stuck on the 1000 entries

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#453]
Number of positions on the Positions list got stuck on the 1000 entries, however, there is more that 1000 positions are already created. 
E.g. there is 932 positions with DAI, 103 positions with USDc and etc. (it is already > that 1000 entries)

Expected Result: show the actual quantity of position (i'm not sure about the positions. however, it would be nice to check the issue for the conditions list as well)

**Comment by mariano-aguero** [comment]
Related to this https://github.com/gnosis/conditional-tokens-explorer/issues/125

**Comment by mariano-aguero** [comment]
See comments https://github.com/gnosis/conditional-tokens-explorer/pull/116#discussion_r475460943
https://github.com/gnosis/conditional-tokens-explorer/pull/98#discussion_r475461927

**Comment by mariano-aguero** [comment]
Added an issue in the subgraph https://github.com/gnosis/hg-subgraph/issues/29

**Comment by elena-zh** [comment]
Verified. Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/656#issuecomment-734839515)
