### ISSUE TITLE
automatically create and keep up-to-date a list of wrapped ERC20 tokens

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#455]
Each wrapped ERC20 token has the same name and symbol, which creates a poor UX when interacting with them in dapps like Uiswap.

We can combat this by creating and maintaining a list of conditional tokens, which can then be imported into Uniswap to provide additional metadata for each token.

Here is an [example list](https://gist.github.com/auryn-macmillan/4aa431933bd86925891815208a9734d9).

Our list should be compatible with, and listed on, [token list](https://tokenlists.org/), here are the [instructions for authoring a list](https://github.com/Uniswap/token-lists#authoring-token-lists).

The list could perhaps be hosted in this repo or on IPFS.

**Comment by mariano-aguero** [comment]
Another example http://tokens.honeyswap.org/
