### ISSUE TITLE
Resolved in Realit.io condition is displayed like an Open one in CTEAF app

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#466]
**Steps**: 
1. Create an Omen condition in CTEAF app 
2. Open Realit.io, search for the condition
3. Resolve it
4. Verify the condition status in the CTEAF app

**Actual Result:** it is still in Open status
![resolved.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a9a13d93-7da0-4321-bded-e723628532ad)

**Expected Result:** the condition is in the Resolved status

(**notes for QA**: not to forget to check a condition resolution date displaying in a condition details when a condition is resolved - #392)

**Comment by mariano-aguero** [comment]
I will close this. If a question was solved doesn't imply that a condition must be solved too
