### ISSUE TITLE
Creation date filter: No validation message when From date > To date (1 day difference)

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#481]
**Steps:**
1. Open Conditions list
2. Open filters
3. Specify in the creation date filter values: 

- From - tomorrow
- To - today

**Actual Result:** no validation message 'To should be greater than From'
![greater.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3d76071c-8952-4745-ad96-5ea9fea09769)

**Expected Result:** 'To should be greater than From' validation message is displayed, user is not allowed to search

**Comment by mariano-aguero** [comment]
@elena-zh I think this is working fine. Can you check it ? thanks
