### ISSUE TITLE
Reporting twice gives 'always failing transaction'

### ISSUE THREAD

**Issue by hpmaxi** [gnosis/conditional-tokens-explorer#488]
Details https://gist.github.com/hpmaxi/7581b90947818737ceee9cc01640bbce

Also, the resolved status isn't updated by the graph so the button is enabled, and in redeem the error of 'condition not resolved' is shown.

**Comment by mariano-aguero** [comment]
@hpmaxi when design was merged, please check if this is still happening

**Comment by hpmaxi** [comment]
This is working right with the new design.

**Comment by elena-zh** [comment]
I have passed the scenario. 
Now the system allows to merge/report only with 'correct' condition. 
The issue is no longer reproducible (except the cases reported in #693, #643, #641, #673)
