### ISSUE TITLE
[UI/UX] - Prepare Omen condition 

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#49]
TBD - Prepare an Omen condition (enter Realitio params instead of the raw bytes of a questionId)

https://wireframepro.mockflow.com/view/M6eaccdb4e3776bf4fd576d04b0095a191590507310129#/page/D0f4574597f6c5880ceafbb9909103580

**Comment by gabitoesmiapodo** [comment]
I think this is already done.

Please confirm and close @cmalfesi @mariano-aguero @lmcorbalan @hpmaxi
