### ISSUE TITLE
Prepare condition: restrict a year input up to 4 numbers in date field on the Prepare Omen condition page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#495]
Related to #434, #491 
See the pic 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7288c137-6d87-4e85-8ad7-36a2c414c019)

It would be nice to limit a year input to 4 digits

**Comment by hpmaxi** [comment]
For uncontrolled components, this seems to be a common issue https://stackoverflow.com/questions/24603919/html5-date-input-6-digit-year
