### ISSUE TITLE
Options to 'show / hide' or 'collapse / expand' columns  in the Positions / Conditions sections

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#500]
After #340 and #493 implementation, Positions list has become horizontally  scrollable because of a huge amount of columns there... And it is not obviously, especially when more that 10 items per page are shown.

I would like to suggest whether 'show/hide' columns functionality or 'collapse/expand'. Or just allow a user to change a column's width.
As another option, implement a dropdown which contains checkboxes with a list of columns a user can select to display (+to show 3-4 columns by default).

**Comment by gabitoesmiapodo** [comment]
This is what we could try to do:

**Design:** https://zpl.io/2yNjvPw

**Workflow:**

- Top right dropdown with options to disable / enable columns.
- Some columns should be fixed (disabled in the dropdown). I haven't made up my mind about which ones yet, but I guess that condition id / position id and the actions' column are a given. Probably we should show at least 4 columns, I don't know.
- User enables / disables the columns they want, the click on "Apply", and the table is updated accordingly. I guess the filters would be reset, but I'm not sure. I have to check that and see how difficult would be to keep them working.
