### ISSUE TITLE
 Positions/Conditions lists: creation date filter shows positions that were created on 'the selected day - 1'

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#502]
See the pic: 
![creation date.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c017901d-43ad-4f7b-a0ee-c6f074fecd40)

The issue is reproducible for the filters on the  Positions and Conditions lists

**Comment by mariano-aguero** [comment]
Mmmm I tried to reproduce it,  without luck

For the positions for the day 20/10/2020, only exist 6:

```
  - PositionId: 0xd48eb8b4c43b34cb05eb1da106a01c559fac691ab2ea50dabe4e5c47012acb2a
    createTimestamp: 1603179408
    date: GMT: Tuesday, 20 October 2020 7:36:48
  - PositionId: 0x3ced90e87004392f45ef0acb3bbd1bbff68245b08166c53212ad10405a97ba39
    createTimestamp: 1603179408
    date: GMT: Tuesday, 20 October 2020 7:36:48
  - PositionId: 0x0e0e1a3be192fd90bf19739151a0b300b2762ac44aea3b92e1e822375c1b48a5
    createTimestamp: 1603179408
    date: GMT: Tuesday, 20 October 2020 7:36:48
  - PositionId: 0xf788bf3aad5ebb87227cef1d8ffdf5abd8070e527ac7c8321d395467e927cc9a
    createTimestamp: 1603202180
    date: GMT: Tuesday, 20 October 2020 13:56:20
  - PositionId: 0x867d5d1f9f6512b5d9a42993f7d8d3cd0472022e19087a6730227ce5b82d2b46
    createTimestamp: 1603202180
    date: GMT: Tuesday, 20 October 2020 13:56:20
  - PositionId: 0x5624515f9383097345ebbeb7ceb34783864dce95a2992daa2c3e605f74e962d7
    createTimestamp: 1603202180
    date: GMT: Tuesday, 20 October 2020 13:56:20
```

When I filter by this day, I have
![Screenshot_20201027_101259](https://user-images.githubusercontent.com/1144028/97307332-50594a00-183e-11eb-9ab0-30f9b922c356.png)

The 6 positions are correct, so I will reduce the priority, 
If someone else has the same problem, I hope with more information it helps to detect the behavior

**Comment by mariano-aguero** [comment]
Also, If I filter by 21/10/2020
![Screenshot_20201027_101314](https://user-images.githubusercontent.com/1144028/97307601-aa5a0f80-183e-11eb-9db1-6e8680e0b5d7.png)

**Comment by davidalbela** [comment]
Looks like I have the same problem 
![cte_filter_date_timezone](https://user-images.githubusercontent.com/3659067/100369160-d6ff7380-3004-11eb-81c4-b71f01e1a96a.png)
