### ISSUE TITLE
Positions  list: Search query hags eternally when switch search options

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#506]
related to #497, #413
**Steps:** 
1 Open positions list
2. Do not fill in the search field
3. Switch search option 

**AR:** Search query is started and hags eternally
https://drive.google.com/file/d/1WF8KyzRnbbaPThfUJaFdk1guQP0rX8rQ/view

**ER:** Don't start a search query when the search field is empty

**Comment by mariano-aguero** [comment]
@elena-zh Can you verify this in develop ? I think was solved by #508

**Comment by elena-zh** [comment]
@mariano-aguero , yes, thanks you. It is not reproducible so far. 
I'm closing the issue.
