### ISSUE TITLE
[UI/UX] Filters alternative view

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#511]
Filters not on the positions or conditions list should look like this.

Design: https://zpl.io/bAL6zWx

**Comment by elena-zh** [comment]
Just no to forget: show reality.eth as an oracle for Omen conditions  in the 'Reporter/Oracle' column in the 'select condition' section
(discussed [here](https://github.com/gnosis/conditional-tokens-explorer/pull/557#issuecomment-719525815) )

**Comment by elena-zh** [comment]
Verified. Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/623#issuecomment-732109249)
