### ISSUE TITLE
[FE] Merge Positions: Select Position 

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#517]
Related to #512

**Comment by gabitoesmiapodo** [comment]
This was already implemented, but I'm moving it to `QA Waiting` so @elena-zh can give this issue her blessings.

**Comment by elena-zh** [comment]
Verified. Notes are [here ](https://github.com/gnosis/conditional-tokens-explorer/pull/571#issuecomment-731218225)
