### ISSUE TITLE
[FE] Report Payouts: Select Condition 

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#519]
Related to #514

**Comment by gabitoesmiapodo** [comment]
This was already implemented, but I'm moving it to `QA Waiting` so @elena-zh can give this issue her blessings.

**Comment by elena-zh** [comment]
Verified. Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/582#issuecomment-731213002)
