### ISSUE TITLE
Positions list: search by Condition ID returns results when search field is filled in with a space

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#528]
Related to #508, #447, #359
**Steps**: 
1. Open Positions list
2. Select search option = condition ID
3. fill in the search field with a space (1)

**Actual Result:** search returns 170 entries
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fb2af8db-10bc-48ce-81f6-60d954f8269f) 

**Expected Result:** No positions found.

**Comment by mariano-aguero** [comment]
I searched in thegraph, using this query

```
{
  positions(first: 1000, where:{conditionIdsStr_contains: " "}) {
    id
    conditionIdsStr
  }
}
```

https://thegraph.com/explorer/subgraph/cag/hg-rinkeby?selected=playground

And I saw some results, for example this exist 
```
0x3dc921e3dde05d089dca654cab6cded582b1dbd8d00c2680b87a3b2b741d8f0a 0xd5041c0efa4f3131e9bc5bff761134c35f0955c5f09b3173b7a26495ab56107a```
And you will be able to see a space in the middle, yes, so I wonder how we can fix this, probably with a hack

**Comment by mariano-aguero** [comment]
I created an issue in the subgraph https://github.com/gnosis/hg-subgraph/issues/28

**Comment by mariano-aguero** [comment]
@elena-zh I think this problem is already solved, can you verify it ?

**Comment by elena-zh** [comment]
@mariano-aguero , yes, it is not reproducible so far. 
I'm closing the issue. 
Thank you!
