### ISSUE TITLE
Display oracle = realit.io for a position when it belongs to an omen condition

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#538]
Related to #527, #355
When we create an omen condition we show oracle = realit.io. 
When we open a related position details, we see oracle = 0x576b76eebe6b5411c0ef310e65de9bff8a60130f . 
**Expected Result**: to show oracle = realit.io in the position's details as well

**Note**: Names (realit.io) should be shown in the lists too

**Comment by mariano-aguero** [comment]
Related to #540
