### ISSUE TITLE
When reporting, only show conditions I can report on

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#544]
When selecting a condition show only conditions where my logged in wallet can report.

**Comment by gabitoesmiapodo** [comment]
@elena-zh https://github.com/gnosis/conditional-tokens-explorer/pull/582 probably addresses this issue.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , yes, it will be implemented in #582
