### ISSUE TITLE
Redemption improvements

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#546]
- When selecting a position with only one condition, auto select the condition.
- Only display conditions which have been resolved
- If a position has been selected, only display conditions that are related.
- If a condition has been selected, only display positions related to the condition that the user has a balance in.
- Display details on question and outcome names for Omen/Reality.eth positions.

**Comment by gabitoesmiapodo** [comment]
Probably invalid after we merge https://github.com/gnosis/conditional-tokens-explorer/pull/597

(@elena-zh please check it)

**Comment by elena-zh** [comment]
@gabitoesmiapodo , cases pp.1-4 are not relevant for the new designed Redeem positions page. 
For the case 5 I have created a separate issue #644

I'm closing the current task.
