### ISSUE TITLE
'Are you sure you want to leave this page?' is not displayed when a conditionID field is filled in with invalid value

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#553]
Related to #211, #537

The issue is reproducible in the next cases:
Condition ID field is filled in with incorrect value on the
 - Split position - split collateral page
 - Merge position page
 - Report payouts page
 - Redeem position page

**Comment by mariano-aguero** [comment]
@elena-zh  Can you check if this is solved with the new design ?

**Comment by elena-zh** [comment]
@mariano-aguero , the issue is solved by the new design implementation. 
I'm closing the bug. 
Thank you!
