### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#554]

**Comment by cmalfesi** [comment]
Validate with @davidalbela the provider and credentials

**Comment by gabitoesmiapodo** [comment]
The feature is already implemented, we only need the Google Analytics ID and to add it to `.env`

**Comment by gabitoesmiapodo** [comment]
@davidalbela @mariano-aguero Not sure if this issue is still valid?

Please close it if it's already implemented.
