### ISSUE TITLE
When disconnected, the app use default Rinkeby for the Network: it causes errors with filtering

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#555]
As a not logged in user, I can see the conditions/positions which are created in the Rinkeby. 
However, my Metamask account is connected to the Mainnet. And If I connect a wallet in the Mainnet, the conditions/positions content is changed. 

**That causes a several issues with filters:** 
1. Search by a custom collateral on the Positions list returns  all the grid values after connection: see the video: https://drive.google.com/file/d/1fZKrWwAAiGjXHvOaLJMeXJc-VsLBo7rK/view
2. Search by a collateral on the Positions list may return an error (search by a wrapped collateral returns error as well after connection):  https://drive.google.com/file/d/1-WMZZXKYpyxhIpzZzPXzEwlzIZdB074u/view
3. Search by a collateral on the Positions list may return no results (the same issue with Condition type filter on the Conditions list): https://drive.google.com/file/d/1KYu6OO2PPIAFDJGJRoUsQL4zABw67yRn/view
4. Search by a REPORTER / ORACLE on the Conditions list may return incorrect results: https://drive.google.com/file/d/1Zoxd6tW8NPs6ofr9XI6XMgzMEEQc5ZLe/view

**Comment by mariano-aguero** [comment]
> As a not logged in user, I can see the conditions/positions which are created in the Rinkeby.
> However, my Metamask account is connected to the Mainnet. And If I connect a wallet in the Mainnet, the conditions/positions content is changed.
> 
> **That causes a several issues with filters:**
> 
> 1. Search by a custom collateral on the Positions list returns  all the grid values after connection: see the video: https://drive.google.com/file/d/1fZKrWwAAiGjXHvOaLJMeXJc-VsLBo7rK/view

@elena-zh I have an answer , What would be the expected result?
I tried to reproduce the problem by executing the follow steps:
- I started the application without being connected, and in the rinkeby network
- I went to the position list
- Filtered by collateral custom
- I checked the expected results, collaterals that aren't in the default configuration 
- I connected my wallet using the mainnet network
- The list was updated with new collaterals, applying the same filters

The image gif ...
![Peek 30-10-2020 13-49](https://user-images.githubusercontent.com/1144028/97734035-6160c000-1ab7-11eb-8595-d1e6dd983ba9.gif)
