### ISSUE TITLE
Empty Condition Id Preview section appears when prepare an omen condition as a not logged in user

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#559]
related to #498, #350
**Steps:** 
1. Disconnect a wallet
2. Open prepare condition page
3. select Omen condition
4. fill in all the required fields with valid data

**AR:** Empty Condition Id Preview section appears 
![condition preview.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/3f5ee3cc-e4f9-49c0-8466-011ca8fd58a2)

**ER:** several options: 
1. show a condition id preview (like it works on the prepare custom condition)
2. OR not to show this section to a not logged in user

**Comment by hpmaxi** [comment]
Closed by #568
