### ISSUE TITLE
'Are you sure you want to leave this page?' pop-up appears after successful position creation/merge

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#560]
Related to #211, #537

**Pop-up appears when:** 
 - split positions and then try to navigate to a position detail (in the same tab)
![position.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c43f4f43-a4ee-4a86-88a9-7111af267850)
 - merge positions and then try to navigate to a position detail (in the same tab)

**Expected Result:** do not show the pop-up in the mentioned above cases

**Comment by mariano-aguero** [comment]
@elena-zh  Can you check if this is solved with the new design ?

**Comment by elena-zh** [comment]
@mariano-aguero , I have rechecked the issue. 
The pop-up is not displayed after successful condition creation/resolve, however, it still appears after successful split/merge when navigate to a created position details in the same tab. 
I have updated the issue description and I'm reopening the bug.

**Comment by mariano-aguero** [comment]
> @mariano-aguero , I have rechecked the issue.
> The pop-up is not displayed after successful condition creation/resolve, however, it still appears after successful split/merge when navigate to a created position details in the same tab.
> I have updated the issue description and I'm reopening the bug.

Thanks, I will work on it
