### ISSUE TITLE
Merge positions: position selection section is not updated when reselect positions to merge 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#564]
The issue will not be relevant, as far as I understand, after #511 implementation.. However, I will report it 

**Steps**: 
1. Create a condition with > 10 outcomes, create positions for the condition
2. Go to the Merge positions page
3. Select 2 positions to merge, then fill in all the required fields on the form
4. Open select positions pop-up and add/remove positions to merge

**AR:** MERGED POSITIONS PREVIEW shows correct values, POSITIONS selection section is not updated
![not updated.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ae7316d5-a144-45a3-8d05-f6046d43bda2)

**ER:** POSITIONS selection section shows correct values

**Comment by mariano-aguero** [comment]
@elena-zh Can you verify this with the new design ? Feel free to close it

**Comment by elena-zh** [comment]
@mariano-aguero , yes, the issue is not relevant to the new design. So, I'm closing it
