### ISSUE TITLE
[Staging+Prod] cDAI icon is blinking when open Collateral filter in the Postitions list

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#577]
https://conditional-tokens-explorer.staging.gnosisdev.com/#/positions 

the same issue was reproducible in the mainnet in Dev (#525)

**Steps:**
1. Open positions list in Rinkeby and search for custom collaterals
2. Scroll to find positions with cDAI collateral --> positions with no icons are displayed
3. Open Collateral dropdown --> cDAI collateral icon appears
(see the video: https://drive.google.com/file/d/1tWgrU7kcDMmHqH4Abv2IPhsRoRaaDLw8/view )

**Expected Result:** the icon is always displayed (and is not a white one)

**Comment by davidalbela** [comment]
There are some code that is looking for `logo.png` with Rinkeby addresses.

Also, we could use the Safe icons instead.

**Comment by mariano-aguero** [comment]
> There are some code that is looking for `logo.png` with Rinkeby addresses.
> 
> Also, we could use the Safe erc-20 icons at S3 bucket instead an extenal github raw endpoint.

@davidalbela please share the package of the safe icons

Also , we need to add a check, the logo only must be fetched if we are connected to the mainnet network
