### ISSUE TITLE
[prod/dev]Split position: the app is crashed when fill in the position field then condition field

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#579]
**Steps:** 
search for a position to split
copy the position id and past it into split position-position field
then search for an open condition id
paste it into the condition field in the split position page

**AR:** the app is crashed 
https://drive.google.com/file/d/11-vL0KST_jqByu4-79m0v-JgxqTXelOT/view

**ER:** the condition is displayed in the field

Note: may be fixed when #511 is implemented

**Comment by mariano-aguero** [comment]
@elena-zh can you check if this is ok ?

**Comment by elena-zh** [comment]
@mariano-aguero , yes, the issue is not relevant in the new split position page.
I'm closing the issue, thank you!
