### ISSUE TITLE
Google Analytics is not working with version 4

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#587]
The library triggers the request, but is not tracking.

See issue https://github.com/react-ga/react-ga/issues/460
https://github.com/react-ga/react-ga/issues/453

**Comment by davidalbela** [comment]
Created an Universal GA property to work with it

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero @davidalbela 

So... does it work?

I could have a look if it doesn't.

Close the issue if it does work.

**Comment by davidalbela** [comment]
Makes sense to close meanwhile we can use `UA-`

**Comment by rchowaniak** [comment]
To explain it perhaps more precisely. Currently in google analytics our accounts are created by default with the prefix `G-` but react-GA work only with `UA-`. Here you can find how to activate your account with `UA-` prefix:
https://www.analyticsmania.com/other-posts/how-to-create-a-universal-analytics-property/

**Comment by mariano-aguero** [comment]
Thanks for your comment, we are using UA and is working good.
