### ISSUE TITLE
reality.eth question id search query not working with lower case hash

### ISSUE THREAD

**Issue by pimato** [gnosis/conditional-tokens-explorer#592]
Just trying to find a condition here:
<img width="620" alt="Bildschirmfoto 2020-11-09 um 13 53 26" src="https://user-images.githubusercontent.com/5337809/98543582-fff8d800-2292-11eb-99a9-2b963afd0887.png">

and it looks like I can`t filter it with the reality.eth question id with lower-case:
```0xae8a4ebade68b4c8d7ab8bc36c12afb32e5bcaeb0d4350e0073b0dc333d3ff8b```

but it is clearly in the list (second item):
<img width="627" alt="Bildschirmfoto 2020-11-09 um 13 54 35" src="https://user-images.githubusercontent.com/5337809/98543742-359dc100-2293-11eb-88f5-4ed299c7400b.png">

**Comment by gabitoesmiapodo** [comment]
I don't think those search fields were working.

Anyways, this and many other issues should be addressed when we finish working on 

https://github.com/gnosis/conditional-tokens-explorer/pull/597 
https://github.com/gnosis/conditional-tokens-explorer/pull/598 
https://github.com/gnosis/conditional-tokens-explorer/pull/583
