### ISSUE TITLE
[UI/UX] Values in the checkboxes (radio buttons) are not center-aligned

### ISSUE THREAD

**Issue by mariano-aguero** [gnosis/conditional-tokens-explorer#599]
Comment from here, https://github.com/gnosis/conditional-tokens-explorer/pull/571#issuecomment-723940788
Point 6

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566353565633937306132653839306563313066373737382f64303532386636352d666232612d343833302d623130662d383039323831393435316566](https://user-images.githubusercontent.com/1144028/98731224-2ba3bd00-237c-11eb-84b1-ae49677fa65f.jpeg)

**Comment by elena-zh** [comment]
Also, I'm adding here one more case: checkbox in the Merge with section is shifted when a position preview is too long
![too long.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1703799b-23b7-4b4f-a4b2-45291becbb6f)

**Comment by gabitoesmiapodo** [comment]
Text wrapping issue's fix is on https://github.com/gnosis/conditional-tokens-explorer/pull/598

**Comment by gabitoesmiapodo** [comment]
Closing because of https://github.com/gnosis/conditional-tokens-explorer/issues/600#issuecomment-725979102
