### ISSUE TITLE
Graphic design

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#6]

**Comment by cmalfesi** [comment]
This is link has the last graphic design version. You can add comments on each screen, just marking an area and write the comment.
https://drive.google.com/drive/folders/1ZgWbkj5Nrwmc-EkUcwx_Xy1uPuyqP_dl?usp=sharing

**Comment by cmalfesi** [comment]
I have shared the designs with Lean and Stefan, of Conditional Tokens Explorer through Figma. I think it is better to add comments. You can navigate with one general click the pages, but adding easily comments. When Gabriel backs form his vacations I will add better navigation.
https://www.figma.com/file/W3hK57rQTH2A6TXrHxYQQh/Contidional-Tokens-Explorer?node-id=0%3A1
Presentation: https://www.figma.com/proto/W3hK57rQTH2A6TXrHxYQQh/Contidional-Tokens-Explorer?node-id=1%3A12&scaling=contain

**Comment by cmalfesi** [comment]
Lea has sent us the feedback:
- she sent the logo added here
[conditonal_tokens_logos.zip](https://github.com/gnosis/conditional-tokens-explorer/files/4932866/conditonal_tokens_logos.zip)
- few suggestions:
--  to simplify the look of the interface and emphasise the selected   section on the top (conditions/positions/etc.), it could be blue and underlined when selected, instead of dark blue and underlined at the moment. Maybe icons could also make it look friendlier  (ex: Gnosis Safe multisig →).
-- This is more a personal preference so I leave it up to you  but I would rather have the dark blue #001428 on most of the text instead of grey (ex: Gnosis Safe multisig →) .
-- on the “prepare conditions” screen there is a message in a blue box (“You need to unlock DAI […]) the thickness of the stroke should match the one of the split button

**Comment by gabitoesmiapodo** [comment]
- Updated logo.
- _"to simplify the look of the interface and emphasise the selected section..."_ -> Ugh, had to update each highlighted item haha... Done, it looks fine I think. I'm not sure about the icons, maybe we should ask Lea if she has some meaningful or official icons related to each section? I don't want to add random icons which we'll need to replace later.
- _"This is more a personal preference so I leave it up to you..."_ -> I tried that, and while the contrast could be beneficial accessibility wise, it looks kind of excessive to me. Maybe it makes the design kind of monotonous? Anyway, I'll leave it as it is for now, and we can change it in the implementation later (where it should be as easy as changing a variable).
- "on the “prepare conditions” screen there is a message in a blue box..." -> Fixed.

Changes should be up on Zeplin now: https://app.zeplin.io/project/5b71fb9cd86c791b1612c035/dashboard?seid=5f049d47ac3d1578f4025577
