### ISSUE TITLE
Report payouts/merge positions: the conditions/positions section is not auto-updated when a condition is resolved/positions merge 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#601]
Related to #582 and #514

When a condition is successfully resolved, the conditions section is not auto-updated and the already resolved condition is still displayed there.

Also, the positions list is not auto-updated after successful positions merge.

It would be nice to reload all these lists

**Comment by mariano-aguero** [comment]
Just to know, the subgraph is not indexing faster enough, so to solve this maybe we need to check some event and that could generate some performance issues

**Comment by elena-zh** [comment]
Note from #657: positions with 0 balance appear in the 'Merge with' section after successful positions merge (the positions list is not auto-reloaded, so when select a position that was merged in the list, Merge with' section will show the merged positions with 0 amounts)
