### ISSUE TITLE
Redeem position: REDEEMED POSITION PREVIEW section always shows 'No redeemed preview yet.'

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#602]
**Steps:** 
Open redeem positions page
fill in the position field 
fill in the RESOLVED CONDITION ID field with a resolved condition for the position 

**Actual Result:** REDEEMED POSITION PREVIEW section always shows 'No redeemed preview yet.'

**Expected Result:** REDEEMED POSITION PREVIEW section shows position preview with an amount to redeem

**Comment by mariano-aguero** [comment]
This should be fixed with the new designs implementation

**Comment by elena-zh** [comment]
The issue is not reproducible in the New design implementation
