### ISSUE TITLE
[object Object] error is displayed when fill in Token Contract Address field with incorrect address in the Mainnet

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#603]
Connect to a wallet in the Mainnet
Go to the split position page
Select a 'Custom' collateral
Fill in the Token Contract Address field with incorrect address (as an example, I filled in with the address of a custom token from the Rinkeby)

**Actual Result:**  [object Object] error is displayed under the field
![object'.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/395e3110-1038-423e-a524-3089f5a08724)

**Expected Result:** Readable error shuld be displayed for a user (smth like 'Error: ENS name not found' or 'Error: Invalid address')

**Comment by gabitoesmiapodo** [comment]
@elena-zh I couldn't get the same results as you, using the same address (I tested it with other addresses too).

On Rinkeby:

![Screen Shot 2020-11-16 at 13 11 18](https://user-images.githubusercontent.com/4015436/99278980-7b680580-280e-11eb-9dab-b031bf414c88.png)

On Mainnet:

![Screen Shot 2020-11-16 at 13 14 28](https://user-images.githubusercontent.com/4015436/99279029-87ec5e00-280e-11eb-8112-08a877cd3023.png)

Other:

![Screen Shot 2020-11-16 at 13 11 31](https://user-images.githubusercontent.com/4015436/99279051-8fac0280-280e-11eb-825d-61e0957c6ba5.png)
![Screen Shot 2020-11-16 at 13 12 04](https://user-images.githubusercontent.com/4015436/99279064-9175c600-280e-11eb-9130-0bbca6c039c3.png)

Could you have a look and check if the problem still exists, or if are there other ways to trigger it?

**Comment by elena-zh** [comment]
@gabitoesmiapodo , indeed, the issue is not reproducible so far. 
I'm closing the issue. 
Thank you!
