### ISSUE TITLE
Filter by collateral: loader is not always displayed when switch between collaterals in the filter

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#604]
See the video. https://drive.google.com/file/d/1XbDRrm1t0AOo-RLwa26f3BsSYc5b34mX/view
For some positions (usdc, owl) loader is displayed, for some (weth, cdai) - not. 
The same issue is reproducible for several colllateral tokens in the Mainnet

**Expected Result:** loader should always appear when list of positions is loaded (according to a filter's selection)

**Comment by mariano-aguero** [comment]
I think this is now working good, can you verify @elena-zh ? Thanks

![mainnet](https://user-images.githubusercontent.com/1144028/100476391-35d7f200-30c4-11eb-94fd-7ee22f7499ed.gif)
![rinkeby](https://user-images.githubusercontent.com/1144028/100476395-37a1b580-30c4-11eb-9781-e76c014fa741.gif)

**Comment by elena-zh** [comment]
@mariano-aguero , yes, now it works fine. 
I'm closing the issue, thank you!
