### ISSUE TITLE
Condition preview section appears when Outcomes field is filled in with incorrect value

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#606]
Related to #350

Each time when  I enter an outcome value which is out of range [2-256], I see Condition preview section, however, it is useless in these cases. 
It would be nice not to show it at all **when an outcome value which is out of range [2-256]**
 ![258.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/61bb2e23-4586-4ef5-8d4a-4f385a69f1b4)

![minus.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/970d2a6b-0728-424b-8112-a3821f338529)

![condition preview.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9c5ccf1d-2a2d-4c6d-b016-1c812f31f4ce)

**Comment by mariano-aguero** [comment]
> Related to #350
> 
> Each time when I enter an outcome value which is iut of range [2-256], I see Condition preview section, however, it is useless in these cases.
> It would be nice not to show it at all
> ![258.jpg](https://camo.githubusercontent.com/5c8f398cba50df32947a6aa95f70e0047517ca494279b72ed6eb1f6656bbfacc/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566353565633937306132653839306563313066373737382f36316262326532332d343538362d346566352d386434612d346633383561363966316234)
> 
> ![minus.jpg](https://camo.githubusercontent.com/c62d9ea69115e5559781062cb6310ae29ee18925c94d6dd4ec09295774260cb6/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566353565633937306132653839306563313066373737382f39373064326136622d303732382d343234622d383131322d613338323166333338353239)
> 
> ![condition preview.jpg](https://camo.githubusercontent.com/210d04b1adeb1baa56f544fdf2569f478b98542b82f70bf9ae2bf3d6f9f8b578/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566353565633937306132653839306563313066373737382f39633563636631642d326132642d346336642d623031362d316338313266333166346365)

Regarding the problem, the condition preview should not be removed, see issue https://github.com/gnosis/conditional-tokens-explorer/issues/350 gnosis request

**Comment by elena-zh** [comment]
> @elena-zh
> Regarding the problem, the condition preview should not be removed, see issue #350 gnosis request

@mariano-aguero , yes, I see. That's my bad that I did not white the clear expected result, but I meant that condition preview should not be displayed when a value in the outcomes field is not in the [2-256] range.

**Comment by mariano-aguero** [comment]
> > @elena-zh
> > Regarding the problem, the condition preview should not be removed, see issue #350 gnosis request
> 
> @mariano-aguero , yes, I see. That's my bad that I did not white the clear expected result, but I meant that condition preview should not be displayed when a value in the outcomes field is not in the [2-256] range.
> 
> I have update the issue description.

Great, let's go ahead
