### ISSUE TITLE
Transaction fails when merge positions with more that 2 conditions

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#611]
Related to #598, #512, #571

Here are the steps: 
condition 1  - 0x036b8db48aebd17d8dae014e37e2db03af33137f1ce80a7f172bc251da3b6bac
with 3 positions: 
	C1 position 1  0x2269228c44ceaed9cdcb0622e2532b38f8eb642f4a59b230ecdbf66e3c306175
	C1 position 2  0x65669480d9f418fbe7a59c2f80cdd6703639f593ae5ff38e00b12fc127ee40d8
	C1 position 3  0xa432aadacd0d09c3f5c29b131d652dd6a96c5ad4d9cc809c2b7d360fcdf8256a
	
	
Condition 2 with 4 outcomes: 0xaf8ec4afa7df9b46cea10cfdcfab35cf1a6b5d00e0427fcb0e3eef1504caac4e

I split position C1P1 under the condition 2 and get 4 positions: 0x2269228c44ceaed9cdcb0622e2532b38f8eb642f4a59b230ecdbf66e3c306175
c2c1p1  0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33
c2c1p2  0x31f767a2bc40ff4303d77168d926e5fecc1b16fecc1f950c7eeb25f99ef4cc5a 
c2c1p3  0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e
c2c1p4  0x4bf76be278029414b3958549ec4c1d7204e2fa6cc9beb43412d7ed453e5a41ce

Condition 1 details: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/867b4804-fc88-4f04-a72d-b36c23d6d3d6)

Condition 2 details: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/930e9709-a88a-4f09-b00e-be1edb73c69c)

**merge c2c1p1**  0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33 
with **c2c1p3**  0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e  under  **condition C1** ---> transaction fails
 
c1 error https://rinkeby.etherscan.io/tx/0xb4d21aecbd0fad263d50e4dc2e8191baa687aa8cf1dd0b88732c5bb5c8642583
![error.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ed78c1cf-9895-42ad-a565-d4b2e63b8f34)

**merge c2c1p1**  0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33 
with **c2c1p3**  0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e  under  **condition C2** ---> transaction fails

c2 error https://rinkeby.etherscan.io/tx/0x7d228b2b39cfc2dd73b3f8972133fd168220fafc75c919fd10f6b7f89c5f2ed2
![error c2.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0e85f514-885a-4113-9ce5-c575f68ec4a6)

**Expected Result:** positions c2c1p1 - c2c1p4 should be merged under  **condition C2* 
 and cannot me merged with condition c1 (as it was in the previous app version)
So, when a user selects the condition 2 to merge, 'Merge' button should be enabled and the transaction should be successful
When a user selects the condition 1 to merge, 'Merge' button should be disabled.

**Comment by elena-zh** [comment]
HI @hpmaxi , I have t reopen the issue as the app is crashed as soon as I select the described in the issue positions to merge
see the video: https://drive.google.com/file/d/1sBi_KJaptAkNcTDKQMSsZd58T1Y4AvuB/view

**Comment by elena-zh** [comment]
HI @hpmaxi , I have created a new conditions and positions and was able to verify the issue. 
The positions are allowed to be merged under an appropriate condition (and a user is not able to select under which one). 
However, the crash for the existing positions (when I select  c2c1p1 0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33 to merge with
with c2c1p3 0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e ) is always reproducible...
Might it be connected with #650? Actually, the error is the same in the console in bot cases 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/05412b46-e315-4389-91dd-0b658386b0f2)

If yes, we can close the current issue...

**Comment by hpmaxi** [comment]
This is solved in #618 , the other issue is described in #650 , and probably solved in #668
