### ISSUE TITLE
UI - double margin between CREATOR ADDRESS and REPORTING ADDRESS sections on a custom reporter condition details

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#628]
See the pic: there is a double margin 20 px between CREATOR ADDRESS and REPORTING ADDRESS sections
![additional padding.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7634ee61-2edf-4b10-8dcb-393f3eb90bc2)

**Expected result:** 1 margin = 20 px.

**Comment by elena-zh** [comment]
Hi @gabitoesmiapodo , I have to reopen the issue: double margin still exists between the section in a custom reporter condition detials
![still.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/408cea6e-251b-430d-9e62-52831f0a5992)

Moreover, it appeared on the custom reporter's position detail
![position.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e7cc1b0a-1f08-4c48-adc1-6c3eb4ca6e23)

Could you please take a look into the issue once again?

**Comment by gabitoesmiapodo** [comment]
@elena-zh I need the condition ID.

**Comment by elena-zh** [comment]
@gabitoesmiapodo 
Position ID 0x12ca05ca3bc2f8a0bbe3c4a876294db533c54670f313e8a563167ad3a46c0ad0
Condition ID 0x4621c84fb3bd26b461a77b1201ff0d009e3dbabb202eb1dde88b54f0a7677fa3

I can open another issue for a position details, if it is needed
