### ISSUE TITLE
Position id is not pre-selected when navigate to the Split position page from Positions list/Position details page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#637]
Related to #583, #515

See the video: position is not pre-selected when navigate to the Split position page (like it works on the current app version)
https://drive.google.com/file/d/1PPTw8Ky5f6eBSWBAM4BGf2utifJ_RozR/view

**Expected Result:** the position should be preselected when navigate to the split position page from Positions list/Position details page

**Comment by gabitoesmiapodo** [comment]
Should be fixed on https://github.com/gnosis/conditional-tokens-explorer/issues/378
