### ISSUE TITLE
Condition id is not pre-selected when navigate to the Merge position page from Conditions list/Condition details page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#639]
Related to #598, #512, #571

Condition id is not pre-selected when navigate to the Merge position page from Conditions list/Condition details page as it worked on the previous app's version. 
When I click on the Merge action button from from Conditions list/Condition details page, I see the list with only mergeable positions (and that is correct), but the mergeable positions are not related to the condition I navigated from 

So, it would be nice... 2 options: 
1. Remove the merge position option from the  Conditions list/Condition details page
OR 
2. Keep it disabled for conditions which do not have mergeable positions. If a condition has mergeable positions, show this positions on the Merge positions page right after navigation

**Comment by gabitoesmiapodo** [comment]
Should be fixed on https://github.com/gnosis/conditional-tokens-explorer/issues/378

**Comment by elena-zh** [comment]
@gabitoesmiapodo , the case does not seem to be a duplicate of #378 due to that case is related to the middle click (and right/left clicks work fine there), while the current indicates that the functionality has stopped working at all after the new design implementation.
However, I might be wrong.

**Comment by gabitoesmiapodo** [comment]
@elena-zh  Yeah, it seems this is more specific. Anyways, it was expected for all these functionalities to stop working, so I'll update #378 to address all the issues.
