### ISSUE TITLE
Position id is not pre-selected when navigate to the Redeem position page from Positions list/Position details page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#640]
Related to #583, #513

Position is not pre-selected when navigate to the Redeem position page (like it works on the current app version)
Right after navigation, positions grid shows all the redeemable positions (if they exist for a connected wallet)

**Expected Result:** 
1. the **Redeemable** position should be preselected when navigate to the Redeem position page from Positions list/Position details page
2. It would be nice to disable Redeem position option on the Positions list/Position details pages when a position is not redeemable

**Comment by gabitoesmiapodo** [comment]
Should be fixed on https://app.zenhub.com/workspaces/conditional-tokens-explorer-5eecb9b75ab924001c8aa224/issues/gnosis/conditional-tokens-explorer/378

**Comment by elena-zh** [comment]
Verified. Now the position is preselected when navigate to the redeem position page from positions list/position details pages. 
I have created a separate issue #646 for the 2nd case (disable Redeem position option when a position is not redeemable)
