### ISSUE TITLE
Empty The reported array is displayed after successful report payouts

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#642]
Related to #598

see the pic: 
![reported array empty.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2dee5fea-5476-41fb-ad7e-c4acc6460735)

**Expected result**: the array should show the payouts values

**Comment by gabitoesmiapodo** [comment]
@elena-zh I think this will be addressed on https://github.com/gnosis/conditional-tokens-explorer/issues/333

It that's the case, please close this issue.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , I'm not really sure that the issues are the same. 
Entry 'The reported array []' was displayed on the previous app version and showed [**1,1,1,1**], as an example (and that means that the issue #333 was implemented). But in the current app version with the new design the array started to show [**nothing**]. And that is my issue.

**Comment by gabitoesmiapodo** [comment]
@elena-zh Good, thank you. Then we should close #333

**Comment by elena-zh** [comment]
**Upd:** the issue is sometimes reproducible. That is why it is reopened. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c889a260-0547-4146-9d1a-96388a3c2ce6)
