### ISSUE TITLE
It would be nice to disable Redeem position option on the Positions list/Position details pages when a position is not redeemable

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#646]
Related to #583, #513, #640 

When click on the Redeem position option on the Positions list/Position details when a position is not redeemable, user is redirected to the Redeem position page and sees 'No positions found.' message in the positions section (a bit confusing)
So it would be nice to disable Redeem position option on the Positions list/Position details pages when a position is not redeemable.

**Comment by hpmaxi** [comment]
@elena-zh Do you have an example position in which this is still happening? Maybe this is closed by #734

**Comment by elena-zh** [comment]
Hi @hpmaxi, no, the issue is fixed by #734, so I'm closing it. 
Thank you!
