### ISSUE TITLE
Add a possibility to reset custom sorting in the select position section

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#648]
Currently, when sort positions by Collateral and Amount columns in the select position section (on the Split position/Merge position/Redeem position pages), it is impossible to reset the sorting to the default one (creation date desc) until page reload.

So it would be nice to implement an option to reset the sorting to the default one

**Comment by hpmaxi** [comment]
@gabitoesmiapodo What do you think about
- Adding a column for creation date
- Or remove sorting by columns here, I talk with Elena about this and she mainly uses the filtering/search to find the position, I do the same.

Also, I don't know which option is more consistent with the new design. 

What I first tried was to add a button 'reset sort' and find a prop of `sortBy: null` but I didn't found anything similar to that, and doesn't seem like a good solution anyway.

**Comment by gabitoesmiapodo** [comment]
@hpmaxi I don't really think we should implement this change.

**Comment by hpmaxi** [comment]
@gabitoesmiapodo I'll close it then.
