### ISSUE TITLE
Gas price shouldn't be hardcoded for redeem

### ISSUE THREAD

**Issue by clesaege** [gnosis/conditional-tokens-explorer#655]
![image](https://user-images.githubusercontent.com/8873352/99689664-2b43aa00-2a7f-11eb-8a47-a8dbdd8e25c0.png)
Gas price for redeem seems hardcoded at 2 500 000 and could frighten people by looking very expensive.

**Comment by mariano-aguero** [comment]
We are working on the integration of the CPK, this will be fixed on https://github.com/gnosis/conditional-tokens-explorer/pull/651

**Comment by mariano-aguero** [comment]
Solved in #651
