### ISSUE TITLE
'Merge with' section shows positions with 0 balance to merge

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#657]
it is an edge case, however, it worth posting. 
Related to #571,#512, #598

**Steps:** 
1. Create a condition with 2 positions
2. Wrap to ERC20 the whole amount of the 1st position
3. Open Merge position page and select 2 position in the positions section

**AR:** 'Merge with' section shows the 1st position with 0 balance. However, a user is not able to complete the merge transaction (due to amount is 0)
![wrap.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/24eb118b-4f39-49c9-86cb-f525d3f874cb)

**ER:** not to show positions with 0 balance in the 'Merge with' section

Also, positions with 0 balance appear in the 'Merge with' section after successful positions merge (the positions list is not auto-reloaded, so when select a position that was merged in the list, Merge with' section will show the merged positions with 0 amounts)

**Comment by mariano-aguero** [comment]
Checking the issue, is not reproducible for me, I attached a gif image displaying the procedure. Regarding list update when something change (a position or a condition) is related to this issue https://github.com/gnosis/conditional-tokens-explorer/issues/601 , 

@elena-zh can you verify the issue 657 is OK ?

![Peek 01-12-2020 15-44](https://user-images.githubusercontent.com/1144028/100783163-36d29180-33ec-11eb-9c95-88843d421862.gif)

**Comment by elena-zh** [comment]
HI @mariano-aguero , I was able to reproduce the issue, however, it is more related to the #601 task: I do not reload Merge positions page and then positions with 0 balance appear in the Merge with section. 
So, the 1st case is not relevant then. I'm closing the current task and have left a comment in #601 not to forget to retest case with 0 positions when the issue is fixed. 
Thank you!
