### ISSUE TITLE
Container is too big when there is no positions for a condition on a condition details page

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#674]
related to #605, #664

**Steps:** 
prepare a condition and open its details

**AR:** Container for related positions is too big
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/56262eab-4706-4b8b-a6c4-eec46e71e53c)

**ER:** container's height is 41 px when there are no positions to display

**Comment by gabitoesmiapodo** [comment]
@elena-zh 

Upon further inspection, I noticed that that's a table, so it looks as it should.

Maybe we shouldn't show anything if there's nothing to show, though? Not sure.

**Comment by elena-zh** [comment]
@gabitoesmiapodo , it might be an option, I think.
