### ISSUE TITLE
Cannot resolve an Omen condition which was created by a currently connected wallet

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#692]
Related to #547, #651

1. Connect a wallet with the app
2. create an Omen condition
3. Open Report payouts page

AR: there is no just created Omen condition in the list of the conditions to report
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d30dbf3b-36a2-497a-9862-46e4ff77407f)

When I adjust filters and find the condition to report, I see a validation message 'The connected user is a not allowed to report payouts' with the disabled Report button
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/9b8b4af4-d009-4aa7-8c92-617e0e656292)

**ER:** user should be able to resolve an Omen condition if it was created by the currently connected wallet

**Comment by mariano-aguero** [comment]
This is not a bug, if a condition is an omen condition, only realitio will be able to report payouts. Only conditions where the connected user is the oracle, can be reported
