### ISSUE TITLE
Redeem is not working (positions are not zero out and no tokens are returned to a wallet)

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#693]
Related to #547, #651

1. create a custom reporter condition
2. create positions for the condition
3. resolve the condition
4. open Redeem positions page and redeem the position

**AR:** transaction is successful, however, position's balance is not zero out, no tokens are returned to the user's wallet

**ER:** transaction is successful, position's balance is zero,  tokens are returned to the user's wallet

**Comment by elena-zh** [comment]
Hey @mariano-aguero , the issue seems to be no longer reproducible. Can I close it?

**Comment by mariano-aguero** [comment]
Yes
