### ISSUE TITLE
There is no link to Omen markets when create an Omen condition

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#703]
1. Open https://omen.eth.link/ and create here a market
2. Open https://conditional-tokens-explorer.dev.gnosisdev.com/ and search for the just created condition (with Omen market)
3. Open the condition details

**AR:** there is no Omen Markets section. Question text is displayed instead of it
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/6451ea01-316f-40bf-ac38-baee4e417a4d)
Omen market https://omen.eth.link/#/0xc8d8d311fe2efac51dc505516a724dfa2a3dde3b

**ER:** Link to Omen markets section should be displayed (where it is relevant)

**Note:** I cannot open market details in Omen right after its creation
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ff28ac08-46be-4f07-b618-02a1cdb5481b)

**Comment by mariano-aguero** [comment]
The omen subgraph is broken, so until it's fixed we cannot verify this problem

**Comment by elena-zh** [comment]
QA note: retest #695 when the issue is fixed.
