### ISSUE TITLE
Do not apply 3 sec of a delay when a date field is filled in with a correct value

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#711]
Related to #698, #709

When I fill in the date filter with a correct value (no matter if manually or using calendar), I have to wait up to 3 sec until the 'Go' error enables. 

**Expected Result:** 2 options
1. remove this delay from the 'Go' button's behavior
2. Or If removal of a delay from the button is not possible, it would be nice to reduce the delay to 1-1,5 sec then as 3 sec is too long to wait...

**Comment by mariano-aguero** [comment]
I will go for the second option
