### ISSUE TITLE
Search results are reset when search for a position while list is loading

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#712]
related to #690, #710, #656

**Steps:** 
1. Open Positions list (or Conditions list)
2. when a grid is still loading. search for a position 

**AR:** search results are displayed. however, in a couple of seconds they are reset (see the [video](https://drive.google.com/file/d/1kcaX6IvD6qr14ibwPXwEH0uDpYt3NWVy/view))

**ER:** search results should remain to be displayed (and should not be reset)

**Comment by mariano-aguero** [comment]
This probably will change with the new design, after that we will analyze what to do.

**Comment by gabitoesmiapodo** [comment]
Search bar changes completely in the new design, closing.
