### ISSUE TITLE
Filtering by the same date can show different results

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#713]
**Steps:** 

1. open conditions list (or positions list)
2. open filter's bar
3. select from date = today (or any other)
4. select to date = today (or any other)
5. run the search
6. open the filter and select from date = today (the same as it is in the filter), run search

**AR:** grid shows another quantity of the search results
https://drive.google.com/file/d/1hVWVyS959gWIAdZVnvnZSHw8moelkgYW/view

**ER:** search results should be the same

**Comment by mariano-aguero** [comment]
Related to #502

**Comment by hpmaxi** [comment]
@elena-zh In the [build for PR #843](https://pr843--conditionaltokensexplorer.review.gnosisdev.com) I can't reproduce this. At first sight, I thought that was related to a denounce query but in the video, it uses the same date twice.

**Comment by elena-zh** [comment]
Hi @hpmaxi , 
I was not able to reproduce the issue in #843 pr as well.
