### ISSUE TITLE
Positions lists: Do not run search when switch search option with empty search field

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#729]
When I switch a search option with empty search field, each time grid is automatically reloaded in a positions list and positions sections. 
See the video https://drive.google.com/file/d/1KQqfCJAwimpVC0_0L2DRfsmLqcPZuVJO/view

**Expected result:** Do not run search when switch search option with empty search field in the positions lists across the app (like it is for th conditions lists)

**Comment by gabitoesmiapodo** [comment]
This one's outdated, we're going to completely change the search bar. Closing.
