### ISSUE TITLE
Inconsistency of the info in a condition and a related position details

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#731]
Related to #628, #695

**Case 1. Omen condition without Omen markets**

Condition details look good. Section with Omen Markets is missing there, question section is displayed.
But when we open the related position details, we do not see the question here, but see the Omen markets section instead. Can we replace Omen markets section with Question section for the related position details?
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f36acfed-bf8a-4c03-997e-775a23a36b8a)

**Case 2. Custom reporter condition**
We are able to see the Question section there.  
But when we open the related position details, Omen markets section is displayed there. Frankly, the Omen markets section for a custom reporter position looks bit weird.. Could it be replaced with Question section at least?
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/d37c530b-150e-436a-92bf-c103e9c6459d)

**As a note and an example:**  Omen condition and positions with Omen markets look good and consistent and do not require any changes
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/cbf57e2f-744b-4a0a-b8c1-2c0feb815d9f)

**Comment by hpmaxi** [comment]
I'm going to need to have resolved gnosis/hg-subgraph#34 first, the logic is done, I will add some mocked data for testing this logic. 
For positions there can be many conditions, so we could need a modal to show all questions as their titles or their ids.
