### ISSUE TITLE
Allow user to switch between authenticated address and CPK addresses

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#735]
To avoid confusing and complicated UX of dealing with EOA/authenticated address and CPK addresses in one view, we decided on the dev sync today that we should allow users to switch between their EOA/authenticated address and any CPK addresses associated with that account.

Users should be able to switch easily between viewing the interface as the EOA/authenticated address and the associated CPK addresses. One option would be with radio buttons in the dropdown.

![image](https://user-images.githubusercontent.com/8453294/101083033-631c1880-357a-11eb-8239-7ebcd2e922cb.png)

CPK would be selected by default, so that it is maximally compatible with Omen.

**Comment by elena-zh** [comment]
use-cases: 
 - prepare condition: "use my wallet' button returns whether CPK address or Metamask address  for the reporting address field
 - condition details: reporting address field shows whether CPK address or Metamask address specified during a condition creation according to the selection
 - transfer outcomes tokens: Send to address should be interpret a value in the field as CPK address or Metamask address  according to the selection
 - split position/merge position/redeem position: positions section should show positions which belong to CPK address or Metamask address  according to the selection
 - report payouts: conditions section should show conditions with reporting address   =  CPK address or Metamask address  according to the selection

**Comment by elena-zh** [comment]
Verified. 
Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/782#issuecomment-762801850)
