### ISSUE TITLE
[UI/UX] - Split Position -  Select Position

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#74]
- Columns to show - TBD
- Add button in Split Position
- Create new modal
- Table (similar to position list)
- Search and filter
- Select Position on click
- Submit

**This will require some extra UI logic (besides the usual business logic)**

**Comment by gabitoesmiapodo** [comment]
This'll probably be solved by what @lmcorbalan 's doing on #75, but we'll know when he's done with it.
