### ISSUE TITLE
Impossible to load conditions list in the Rinkeby

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#752]
Open the Conditions list --> loader is displayed there, no conditions appear in the list. error in console is displayed:
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/817d6745-81b3-44a4-bf7b-2ca9def4327f)

**ER:** list is loaded

**Comment by davidalbela** [comment]
Related with https://github.com/gnosis/hg-subgraph/issues/35
