### ISSUE TITLE
Update cookie banner

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#756]
The current cookie banner gives users the option to accept or dismiss the banner.
![image](https://user-images.githubusercontent.com/8453294/101911005-c5ce6f00-3b8d-11eb-8394-fc87a021e771.png)

This needs to be updated so that:
1. Analytics cookies (GA) are disabled by default, but can be opted in to.
2. Any necessary cookies cannot be deselected.

See this example from Gnosis Safe
![image](https://user-images.githubusercontent.com/8453294/101911086-e26aa700-3b8d-11eb-9f25-27d0e1f2dabe.png)
And this example from another product
![image](https://user-images.githubusercontent.com/8453294/101911235-19d95380-3b8e-11eb-8b2d-659b7a6e8421.png)

**Comment by elena-zh** [comment]
Verified. Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/pull/775#issuecomment-750016657)
