### ISSUE TITLE
[UI/UX] - Implement a new design (Need specs)

### ISSUE THREAD

**Issue by cmalfesi** [gnosis/conditional-tokens-explorer#760]
Here is a really quick mockup of what I'm imagining for the UI
https://www.figma.com/file/NKdZKp1kKzwW2fiJrD3n05/CTE-UI-update?node-id=0%3A1 (editado) 
Still needs to be fleshed out more, but it should be fairly illustrative.

**Comment by gabitoesmiapodo** [comment]
I'm closing this, changing Auryn's initial issue to an epic, and creating several issues for each new design.
