### ISSUE TITLE
Expand conditions details section to remove scroll in the CONDITION'S SPLIT POSITIONS section

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#766]
this  is related to #763.
After adding a column with an outcome collection, scroll is displayed in the  CONDITION'S SPLIT POSITIONS section, and now it is difficult to see positions amounts at a glance. 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/7f085231-5f97-4a77-86ab-a2ac93fcfad1)

As an option, I would propose to expand condition's details area in order to remove scroll...
![without scroll.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0ee56278-9290-4533-9336-eb1f773b51ee)

**Comment by gabitoesmiapodo** [comment]
@elena-zh scroll bars are there for these cases. We won't change the main container's width for now, mainly for two reasons:  keeping consistency and because we are planning on implementing a better layout for this in the future (there's a lot of information now that's wasn't there in the past).
