### ISSUE TITLE
Transaction is failed when merge 'deeper' positions

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#790]
Related to #789

1 create a condition
2. split positions for it (C1P1+C1P2)
3. create condition C2
4. split: condition C2+ select position option (and use C1P1). Do not split the whole amount. split 1 token, as an example (**C2C1P1-1** +**C2C1P1-2** + **C2C1P1-3**)
5. Merge **C2C1P1-1** +**C2C1P1-2** = **C2C1P1-1/2**
6. Try to merge **C2C1P1-1/2**  +**C2C1P1-3**

**AR:** impossible. see the image
![fail.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/218e2ebe-8448-4071-a7c3-f2a9f4e9392f) 

**ER**: transaction is successful, tokens return back to the position C1P1

**Comment by elena-zh** [comment]
Here are the IDs (if needed)
C1  - 0xa13fcebd772593e0e7ee223c591557993b902d0e22fae8b9ffe936fb1022c2ad
C1P1 0xa34678e9018e709faf809ab90f4a762fdb3197b5d11ec3e3d143a8b44f6887fd
C1P2 0x6256ddce8803eec6a1bb91f84fc0de28c99cb0cab0579d3b3f593c13032ecaf7

C2  - 0x20c5b4853008b74f874b03728d2726914f0c352e5f319a4438b6b5a1e3f4863c + C1P1 = 
C2C1P1-1  0x48e9f296f7009197634b7d4becaec6a1560017bb27cdba00febc9aa5a62d95b1
C2C1P1-2 0x369d8b92d38e488b5461e3d992a693e931c74c27b1224b42058241af3f505900
C2C1P1-3 0xabfcb128f015dca39657322396aa003b9b25995e831c1e2e75cb48842635c6e9


Merge  C2C1P1-1 + C2C1P1-2 = C2C1P1-1/2
0x48e9f296f7009197634b7d4becaec6a1560017bb27cdba00febc9aa5a62d95b1 + 0x369d8b92d38e488b5461e3d992a693e931c74c27b1224b42058241af3f505900 = 0xe00eacc18bf34b9f51ee96f13edd4a0984af1cbe056cf5faadfc760e919f7ea9



Merge C2C1P1-1/2 + C2C1P1-3
0xe00eacc18bf34b9f51ee96f13edd4a0984af1cbe056cf5faadfc760e919f7ea9 + 0xabfcb128f015dca39657322396aa003b9b25995e831c1e2e75cb48842635c6e9 = **impossible**

**Comment by hpmaxi** [comment]
I will check if this is related to checking if parentCollection is null in cpk service.

**Comment by elena-zh** [comment]
Thank you, @hpmaxi !
I will add some notes: transaction fails even if merge all 3 positions of a deeper level at a time (without an intermediate step with merging 2 of them first). E.g. 
1 create a condition
2. split positions for it (C1P1+C1P2)
3. create condition C2
4. split: condition C2+ select position option (and use C1P1). Do not split the whole amount. split 1 token, as an example (C2C1P1-1 +C2C1P1-2 + C2C1P1-3)
5. Merge C2C1P1-1 +C2C1P1-2 +C2C1P1-3 ==> fail
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fabb138b-cb2d-466a-aa1a-e3344d5b460e)

**Comment by elena-zh** [comment]
No longer reproducible - fixed in #802 PR
