### ISSUE TITLE
[Regression] app is not reloaded, disconnected when change connection settings in the app connected via WalletConnect 

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#794]
The issue has become reproducible in **DEV** only. In Staging and in Prod the issue is not reproducible and all the scenarios work as expected. 

1. Connect the app using WalletConnect (I connected with mobile Metamask), then change an account in the mobile Metamask --> the app is not auto-reloaded. The account is changed only after manual app reload. 
**ER:** the app should be auto-reloaded when the account is changed in the connected app.

2. Connect the app using WalletConnect (I connected with mobile Metamask), then change a network in the mobile Metamask (from Rinkeby to Mainnet) --> the app is not auto-reloaded. The network is changed only after manual app reload. 
**ER:** the app should be auto-reloaded when the network is changed in the connected app.

3. Connect the app using WalletConnect (I connected with mobile Metamask), then close the connection in the mobile Metamask (from Rinkeby to Mainnet) --> the app is not auto-reloaded. The app remains to be connected to a wallet. When I reload the page, a connection modal appears which requires to resore the connection, otherwise you cannot proceed to work with the app.
**ER:**  the app should be auto-disconnected with the wallet.

**Comment by elena-zh** [comment]
Hey @mariano-aguero !
The issue is fixed in #782 pr, I have just verified it.

**Comment by mariano-aguero** [comment]
> Hey @mariano-aguero !
> The issue is fixed in #782 pr, I have just verified it.

Excellent!! Thanks for your effort!
