### ISSUE TITLE
CTE app is not disconnected when logout from the connected app

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#795]
The issue is reproducible when the CTE connected via WalletConenct

**Steps**: 
1. Connect the app using WalletConnect
2. Logout from the connected via WalletConnect app

**AR**: the app is not auto-reloaded and remains to be connected to a wallet.

**ER**: the app should be auto-disconnected with the wallet.

**Comment by elena-zh** [comment]
@mariano-aguero , the issue, related to the connection with metamask, is fixed in #782.
However, the case with WalletConnect is still threre:

1. Connect the app using wallet connect
2. Logout from the connected via  WalletConnect app --> the CTE app remains to be connected.

So, it would be great to fix this issue.

**Comment by hpmaxi** [comment]
Tested with metamask mobile on xDai and Rinkeby, and is working.

**Comment by elena-zh** [comment]
@hpmaxi , I'm able to reproduce the issue. 
Please, follow the next steps: 
1. connect the via wallet connect with metamask mobile
2. then Log out from the metamask mobile
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/92acd400-4038-468e-acae-8798f16cb057)

You will be logged out from the metamask mobile, however, you will be still connected in the CTE app
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fd0b6e27-75a6-42cb-8101-79a5c10c09c3)

**Comment by hpmaxi** [comment]
@elena-zh Metamask doesn't remove sessions on log out. I tried sending a tx as a logged out user and I found it after login again waiting for confirmation.

In Settings > Experimental > Wallet Connect Sessions > Press. 

![fdf9379e-9b6a-47aa-9734-172eb6bf1ffa.jpeg](https://images.zenhubusercontent.com/5cbf252f51a0ad0875a2ffc1/60aad39b-f46a-45ed-b7b1-41aeba35ea3a)

And remove the session.
